/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.supermarket.calculator;

public final class R {
    public static final class array {
        public static final int grocery_items=0x7f060000;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int accent=0x7f040002;
        public static final int addBtn=0x7f040009;
        public static final int background=0x7f040003;
        public static final int blueDark=0x7f04001b;
        public static final int bluePrimary=0x7f04001a;
        public static final int budgetDefault=0x7f040013;
        public static final int budgetPositive=0x7f040015;
        public static final int budgetWarning=0x7f040014;
        public static final int cardBg=0x7f040004;
        public static final int clearBtn=0x7f04000a;
        public static final int darkBg=0x7f040016;
        public static final int darkCard=0x7f040017;
        public static final int darkTextPrimary=0x7f040018;
        public static final int darkTextSecondary=0x7f040019;
        public static final int divider=0x7f040008;
        public static final int finishBtn=0x7f04000b;
        public static final int headerBg=0x7f04000d;
        public static final int headerText=0x7f04000e;
        public static final int highlightBg=0x7f04001e;
        public static final int numpadBgDefault=0x7f04001c;
        public static final int numpadBgRounded=0x7f04001d;
        public static final int paidHighlight=0x7f04001f;
        public static final int primary=0x7f040000;
        public static final int primaryDark=0x7f040001;
        public static final int qtyBtnBg=0x7f040011;
        public static final int removeBtn=0x7f04000c;
        public static final int rowEven=0x7f04000f;
        public static final int rowOdd=0x7f040010;
        public static final int textPrimary=0x7f040005;
        public static final int textSecondary=0x7f040006;
        public static final int totalColor=0x7f040007;
        public static final int white=0x7f040012;
    }
    public static final class drawable {
        public static final int bg_action_rounded=0x7f020000;
        public static final int bg_budget_highlight=0x7f020001;
        public static final int bg_concluir_neon=0x7f020002;
        public static final int bg_input=0x7f020003;
        public static final int bg_input_dark=0x7f020004;
        public static final int bg_numpad_rounded=0x7f020005;
        public static final int bg_pago_badge=0x7f020006;
        public static final int bg_pendente_badge=0x7f020007;
        public static final int bg_qty_btn=0x7f020008;
        public static final int bg_tab_active=0x7f020009;
        public static final int btn_action=0x7f02000a;
        public static final int btn_numpad=0x7f02000b;
        public static final int ic_launcher=0x7f02000c;
    }
    public static final class id {
        public static final int addButton=0x7f08001d;
        public static final int addExpenseBtn=0x7f080033;
        public static final int btnConcluirPaid=0x7f08002e;
        public static final int btnGroceryDropdown=0x7f08000c;
        public static final int btnN0=0x7f08001f;
        public static final int btnN00=0x7f08001e;
        public static final int btnN1=0x7f08001a;
        public static final int btnN2=0x7f08001b;
        public static final int btnN3=0x7f08001c;
        public static final int btnN4=0x7f080016;
        public static final int btnN5=0x7f080017;
        public static final int btnN6=0x7f080018;
        public static final int btnN7=0x7f080012;
        public static final int btnN8=0x7f080013;
        public static final int btnN9=0x7f080014;
        public static final int btnNBack=0x7f080015;
        public static final int btnNClear=0x7f080019;
        public static final int btnNComma=0x7f080020;
        public static final int btnOpAdd=0x7f080023;
        public static final int btnOpDiv=0x7f080026;
        public static final int btnOpEq=0x7f080027;
        public static final int btnOpMul=0x7f080025;
        public static final int btnOpSub=0x7f080024;
        public static final int budgetLimitDisplay=0x7f08002a;
        public static final int budgetRemaining=0x7f08002b;
        public static final int budgetRow=0x7f080029;
        public static final int calculatorPage=0x7f080008;
        public static final int cartList=0x7f080009;
        public static final int chkShow00=0x7f08005a;
        public static final int chkShowBack=0x7f080058;
        public static final int chkShowClear=0x7f080059;
        public static final int chkShowOps=0x7f080057;
        public static final int clearButton=0x7f080021;
        public static final int decBtn=0x7f080061;
        public static final int decQtyBtn=0x7f08000e;
        public static final int emptyExpReportsText=0x7f08004c;
        public static final int emptyExpensesText=0x7f080035;
        public static final int emptyView=0x7f08000a;
        public static final int expFinanceBudgetDisplay=0x7f080051;
        public static final int expFinanceContent=0x7f08002f;
        public static final int expFinanceFilesContent=0x7f08004a;
        public static final int expFinancePaidValue=0x7f08004f;
        public static final int expFinanceRemainingValue=0x7f080050;
        public static final int expFinanceSummaryRow=0x7f08004d;
        public static final int expFinanceTotalValue=0x7f08004e;
        public static final int expMarketContent=0x7f080042;
        public static final int expMarketEmptyText=0x7f080044;
        public static final int expMarketListView=0x7f080043;
        public static final int expReportsListView=0x7f08004b;
        public static final int expTabFinance=0x7f080041;
        public static final int expTabMarket=0x7f080040;
        public static final int expenseAmount=0x7f080031;
        public static final int expenseCategoryBtn=0x7f080032;
        public static final int expenseClearBtn=0x7f080038;
        public static final int expenseDesc=0x7f080030;
        public static final int expenseExportBtn=0x7f080037;
        public static final int expenseListView=0x7f080034;
        public static final int expensePaidDisplay=0x7f08003d;
        public static final int expenseRemainingDisplay=0x7f08003e;
        public static final int expenseReportBtn=0x7f080036;
        public static final int expenseTotalDisplay=0x7f08003c;
        public static final int expensesPage=0x7f08003f;
        public static final int financeBudgetLimitDisplay=0x7f08003a;
        public static final int financeBudgetRemaining=0x7f08003b;
        public static final int financeBudgetRow=0x7f080039;
        public static final int finishButton=0x7f08002c;
        public static final int headerBar=0x7f080001;
        public static final int incBtn=0x7f080063;
        public static final int incQtyBtn=0x7f080010;
        public static final int itemCount=0x7f080002;
        public static final int itemName=0x7f08005f;
        public static final int itemPaidCheck=0x7f08005e;
        public static final int itemPaidStatus=0x7f080064;
        public static final int itemQty=0x7f080062;
        public static final int itemTotalPrice=0x7f080066;
        public static final int itemUnitPrice=0x7f080065;
        public static final int marketAmountInput=0x7f080047;
        public static final int marketApplyBtn=0x7f080048;
        public static final int marketCancelBtn=0x7f080049;
        public static final int marketSelectionBar=0x7f080045;
        public static final int marketSelectionCount=0x7f080046;
        public static final int numpadContainer=0x7f080011;
        public static final int opsRow=0x7f080022;
        public static final int priceDisplay=0x7f08000d;
        public static final int productNameInput=0x7f08000b;
        public static final int qtyContainer=0x7f080060;
        public static final int qtyDisplay=0x7f08000f;
        public static final int removeBtn=0x7f080067;
        public static final int rootLayout=0x7f080000;
        public static final int savedItemCheck=0x7f08006b;
        public static final int savedItemDate=0x7f080069;
        public static final int savedItemDelete=0x7f08006d;
        public static final int savedItemLoad=0x7f08006a;
        public static final int savedItemName=0x7f080068;
        public static final int savedItemShare=0x7f08006c;
        public static final int savedListsPage=0x7f08002d;
        public static final int settingsPage=0x7f080052;
        public static final int skinDefault=0x7f08005c;
        public static final int skinGroup=0x7f08005b;
        public static final int skinRounded=0x7f08005d;
        public static final int tabBar=0x7f080003;
        public static final int tabCalculator=0x7f080004;
        public static final int tabExpenses=0x7f080006;
        public static final int tabSavedLists=0x7f080005;
        public static final int tabSettings=0x7f080007;
        public static final int themeBlue=0x7f080056;
        public static final int themeDark=0x7f080055;
        public static final int themeDefault=0x7f080054;
        public static final int themeGroup=0x7f080053;
        public static final int totalDisplay=0x7f080028;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int activity_splash=0x7f030001;
        public static final int cart_item=0x7f030002;
        public static final int saved_list_item=0x7f030003;
    }
    public static final class string {
        public static final int add=0x7f050001;
        public static final int app_name=0x7f050000;
        public static final int budget_approaching=0x7f050016;
        public static final int budget_click_hint=0x7f050011;
        public static final int budget_dialog_clear=0x7f050014;
        public static final int budget_dialog_title=0x7f050013;
        public static final int budget_exceeded=0x7f050015;
        public static final int budget_label=0x7f05000f;
        public static final int budget_remaining=0x7f050012;
        public static final int budget_set=0x7f050010;
        public static final int cart_title=0x7f050007;
        public static final int clear_all=0x7f050002;
        public static final int compare_btn=0x7f05003c;
        public static final int compare_common=0x7f05003d;
        public static final int compare_decreased=0x7f050044;
        public static final int compare_increased=0x7f050043;
        public static final int compare_new_item=0x7f050046;
        public static final int compare_no_diff=0x7f050041;
        public static final int compare_only_first=0x7f05003e;
        public static final int compare_only_second=0x7f05003f;
        public static final int compare_removed_item=0x7f050047;
        public static final int compare_same=0x7f050045;
        public static final int compare_select_both=0x7f050042;
        public static final int compare_select_first=0x7f05003a;
        public static final int compare_select_second=0x7f05003b;
        public static final int compare_title=0x7f050039;
        public static final int compare_total=0x7f050040;
        public static final int custom_saved=0x7f050030;
        public static final int empty_cart=0x7f05000a;
        public static final int exp_add=0x7f050055;
        public static final int exp_amount_hint=0x7f050054;
        public static final int exp_cat_condo=0x7f050067;
        public static final int exp_cat_education=0x7f05006a;
        public static final int exp_cat_energy=0x7f050062;
        public static final int exp_cat_gas=0x7f050063;
        public static final int exp_cat_insurance=0x7f05006c;
        public static final int exp_cat_internet=0x7f050065;
        public static final int exp_cat_leisure=0x7f05006b;
        public static final int exp_cat_other=0x7f05006e;
        public static final int exp_cat_pharmacy=0x7f050068;
        public static final int exp_cat_phone=0x7f050064;
        public static final int exp_cat_rent=0x7f050066;
        public static final int exp_cat_subs=0x7f05006d;
        public static final int exp_cat_transport=0x7f050069;
        /**  Accounting expense categories 
         */
        public static final int exp_cat_water=0x7f050061;
        public static final int exp_clear=0x7f050059;
        public static final int exp_delete_confirm=0x7f05005e;
        public static final int exp_desc_hint=0x7f050053;
        public static final int exp_empty=0x7f050056;
        public static final int exp_export=0x7f050058;
        public static final int exp_exported=0x7f05005c;
        public static final int exp_invalid=0x7f05005d;
        public static final int exp_market_empty=0x7f050070;
        /**  Market sub-tab 
         */
        public static final int exp_market_header=0x7f05006f;
        public static final int exp_market_item_count=0x7f050071;
        public static final int exp_report=0x7f050057;
        public static final int exp_report_title=0x7f05005b;
        public static final int exp_summary_combined=0x7f050075;
        public static final int exp_summary_finance=0x7f050074;
        /**  Summary sub-tab 
         */
        public static final int exp_summary_header=0x7f050072;
        public static final int exp_summary_market=0x7f050073;
        public static final int exp_summary_no_data=0x7f050076;
        public static final int exp_tab_finance=0x7f050060;
        /**  Expense sub-tabs 
         */
        public static final int exp_tab_market=0x7f05005f;
        public static final int exp_total_label=0x7f05005a;
        public static final int expenses_title=0x7f050052;
        public static final int fill_fields=0x7f05000d;
        public static final int finish=0x7f050003;
        public static final int finish_title=0x7f05001a;
        public static final int grocery_dropdown_hint=0x7f05002e;
        public static final int header_subtitle=0x7f050009;
        public static final int header_title=0x7f050008;
        public static final int invalid_price=0x7f05000e;
        /**  Saved list title 
         */
        public static final int list_title_hint=0x7f05004a;
        public static final int listas_tab_compare=0x7f050032;
        public static final int listas_tab_lists=0x7f050031;
        public static final int listas_tab_templates=0x7f050033;
        public static final int load_as_template=0x7f050035;
        public static final int load_list=0x7f050034;
        public static final int new_title_hint=0x7f050050;
        public static final int no_saved_lists=0x7f050020;
        public static final int no_templates=0x7f050049;
        public static final int ok=0x7f05000c;
        public static final int price_hint=0x7f050005;
        public static final int product_hint=0x7f050004;
        public static final int quick_added=0x7f05002f;
        public static final int receipt_title=0x7f05000b;
        public static final int rename_dialog_title=0x7f05004f;
        public static final int rename_list=0x7f05004e;
        public static final int save_as_template=0x7f050036;
        public static final int save_error=0x7f050019;
        public static final int save_list=0x7f050017;
        public static final int save_success=0x7f050018;
        public static final int save_title_default=0x7f05004d;
        public static final int save_title_dialog=0x7f05004b;
        public static final int save_title_hint=0x7f05004c;
        public static final int saved_lists_title=0x7f05001f;
        public static final int settings_about=0x7f05002d;
        public static final int settings_keyboard=0x7f050025;
        public static final int settings_show_00=0x7f050029;
        public static final int settings_show_back=0x7f050027;
        public static final int settings_show_clear=0x7f050028;
        public static final int settings_show_ops=0x7f050026;
        public static final int settings_skin=0x7f05002a;
        public static final int settings_skin_default=0x7f05002b;
        public static final int settings_skin_rounded=0x7f05002c;
        public static final int settings_theme=0x7f050021;
        public static final int settings_theme_blue=0x7f050024;
        public static final int settings_theme_dark=0x7f050023;
        public static final int settings_theme_green=0x7f050022;
        public static final int share_list=0x7f05001b;
        public static final int tab_calculator=0x7f05001c;
        /**  Financial Expenses 
         */
        public static final int tab_expenses=0x7f050051;
        public static final int tab_lists=0x7f05001d;
        public static final int tab_settings=0x7f05001e;
        public static final int template_loaded=0x7f050038;
        public static final int template_name_hint=0x7f050048;
        public static final int template_saved=0x7f050037;
        public static final int total_label=0x7f050006;
    }
    public static final class style {
        public static final int AppTheme=0x7f070000;
    }
}
