import '../../models/midia_model.dart';
import 'midia_repository.dart';

/// Repositorio local espelhado do catalogo real (gerado a partir de
/// database/seed_tmdb.sql via scripts/_espelhar_mock.py). Permite
/// desenvolver, testar e operar em fallback sem depender do Supabase.
/// IDs sao UUID v5 deterministicos (estaveis entre regeneracoes).
class MockMidiaRepository implements MidiaRepository {
  const MockMidiaRepository();

  static const List<Map<String, dynamic>> _seed = [
    {
      'id': 'e209ea1e-d7b3-5f4b-92be-1ad4aad56d04',
      'titulo': 'Spider-Man: Brand New Day',
      'tipo': 'filme',
      'categoria': 'Science Fiction',
      'sinopse': 'Fighting crime full-time as Spider-Man in a world that doesn\'t remember him—and the pressure of seeing his old friends move on without him—sparks a change in Peter Parker he may not have the power to control. But that transformation might also be the only thing that can stop a shocking new threat to the city and those he loves - a powerful villain no one can even see.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/iPOn6DinuVyLY17YM9mKuPofV08.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg',
      'ano': 2026,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '6a9d859c-16ee-5a80-86f9-5b609de798bd',
      'titulo': 'The Odyssey',
      'tipo': 'filme',
      'categoria': 'Adventure',
      'sinopse': 'Odysseus, the legendary King of Ithaca, embarks on a long and perilous journey home following the Trojan War. Throughout his voyage, he is forced to confront the whims of gods, mythological monsters, and trials that stretch both his cunning and his humanity to the breaking point.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/RMXG8myu1aGlNUsRjtxzmpdMK0.jpg',
      'ano': 2026,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '8ec08bdd-93bc-52c5-a657-194142f23134',
      'titulo': 'Spider-Man: No Way Home',
      'tipo': 'filme',
      'categoria': 'Action',
      'sinopse': 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg',
      'ano': 2021,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': 'b1fa80e6-ef90-5f47-93a5-afdf7ac5c8c5',
      'titulo': 'Supergirl',
      'tipo': 'filme',
      'categoria': 'Action',
      'sinopse': 'When an unexpected and ruthless adversary strikes too close to home, Kara Zor-El, aka Supergirl, reluctantly joins forces with an unlikely companion on an epic, interstellar journey of vengeance and justice.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/1QCWdqzTfh2x9UylVpspIU6QTuM.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/4X2YSe8PaYbsBqX3TDmmIU4vOju.jpg',
      'ano': 2026,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '3adc9864-a765-57f5-b386-b016f91b52de',
      'titulo': 'Disclosure Day',
      'tipo': 'filme',
      'categoria': 'Science Fiction',
      'sinopse': 'A cybersecurity expert becomes a whistleblower after uncovering secrets about aliens, putting him on the run from a corporation. Meanwhile, a meteorologist experiencing strange phenomena joins forces with him to prove there\'s life beyond our understanding.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/AnJ8IQJI23hNpYXVNaythu061Ru.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/flxau5Iu7bChQHsESqvGZ3FQRaI.jpg',
      'ano': 2026,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '53825cdb-bef0-5975-a927-97efc047cb87',
      'titulo': 'Obsession',
      'tipo': 'filme',
      'categoria': 'Horror',
      'sinopse': 'After breaking the mysterious "One Wish Willow" to win his crush\'s heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg',
      'ano': 2026,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '34ad7185-0f63-53e5-9e15-f58d9e4b21fb',
      'titulo': 'Toy Story 5',
      'tipo': 'filme',
      'categoria': 'Animation',
      'sinopse': 'When Bonnie receives a Lilypad tablet as a gift and becomes obsessed, Buzz, Woody, Jessie and the rest of the gang\'s jobs become exponentially harder when they have to go head to head with the all-new threat to playtime.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/sfQtVlIHljToOwYjhe21KPGzZWK.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/8sSKdEmlmqF4kJUd28SqthXC4yZ.jpg',
      'ano': 2026,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '436df2b0-d38a-58f6-81fa-87d691427899',
      'titulo': 'The Death of Robin Hood',
      'tipo': 'filme',
      'categoria': 'Adventure',
      'sinopse': 'Grappling with his past after a life of crime and murder, Robin Hood finds himself gravely injured after a battle he thought would be his last. In the hands of a mysterious woman, he is offered a chance at salvation.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/92Tsfx7SFafOqWsotvrlJbHyehd.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/lh3BDkmWJh998n4fQcHYcVi7dpm.jpg',
      'ano': 2026,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '61c83319-f6d2-53fa-bd71-36ddded51952',
      'titulo': 'Moana',
      'tipo': 'filme',
      'categoria': 'Family',
      'sinopse': 'Teenage Moana answers the Ocean\'s call and, for the first time, voyages beyond the reef of her island of Motunui with infamous demigod Maui on an unforgettable journey to restore prosperity to her people.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg',
      'ano': 2026,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 0,
      'popularidade': 100,
    },
    {
      'id': 'd005c801-0abd-5bf2-a12e-a58d1489e559',
      'titulo': 'Minions & Monsters',
      'tipo': 'filme',
      'categoria': 'Adventure',
      'sinopse': 'This is the rambunctious, ridiculous and totally true story of how the Minions conquered Hollywood, became movie stars, lost everything, unleashed monsters onto the world and then banded together to try and save the planet from the mayhem they had just created.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/nz7i42yhLIJ4ve9JKgM6NthoLHO.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/kkcwhgSFd81QDlXo8ytrpHPQjhy.jpg',
      'ano': 2026,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '1a5c827e-a9e0-572d-8b55-fa33ed566ed4',
      'titulo': 'Masters of the Universe',
      'tipo': 'filme',
      'categoria': 'Action',
      'sinopse': 'After being separated for 15 years, the Sword of Power leads Prince Adam back to Eternia, where he discovers his home shattered under the fiendish rule of Skeletor. To save his family and his world, Adam must join forces with his closest allies, Teela and Duncan/Man-At-Arms, and embrace his true destiny as He-Man — the most powerful man in the universe.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/oRuyGUHdoaQxWP3SDfafGkStxTC.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/yQIdU11DYQQp0neGtGtGxbGfRer.jpg',
      'ano': 2026,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '06732440-dc00-5ba7-b535-8ff37567fced',
      'titulo': 'The Devil\'s Mouth',
      'tipo': 'filme',
      'categoria': 'Horror',
      'sinopse': 'A group of college friends\' Thailand adventure turns deadly when they become trapped in submerged caves with a dangerous predator. As oxygen runs low, past conflicts emerge in their desperate fight for survival.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/lH8k9uCWYn2b2gsYleqYBDPbWa8.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/se8LfmZYFiNerF6U7zMUKePV0vE.jpg',
      'ano': 2026,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '35793011-81f3-50d3-9a58-8b135cd7a3bd',
      'titulo': 'Colony',
      'tipo': 'filme',
      'categoria': 'Action',
      'sinopse': 'Professor Se-jeong is thrust into a bloody nightmare when a rapidly mutating virus is released during a biotech conference causing authorities to seal the facility. Trapped inside with no escape, Se-jeong along with a small group of survivors must fight to stay alive while the infected undergo horrific transformations.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/tN799oUR0f1gUKDYdMNrDaY7I51.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/jDvxsBemt2Iyslg7qn2WMzgxz23.jpg',
      'ano': 2026,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '1c151c68-6583-5c5f-ab93-3065ebf2905f',
      'titulo': 'Spider-Man: Homecoming',
      'tipo': 'filme',
      'categoria': 'Action',
      'sinopse': 'Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/fn4n6uOYcB6Uh89nbNPoU2w80RV.jpg',
      'ano': 2017,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': 'd0859c61-8e46-5aa1-83f3-29f53496d32a',
      'titulo': 'Evil Dead Burn',
      'tipo': 'filme',
      'categoria': 'Horror',
      'sinopse': 'After her husband\'s abrupt death, Alice seeks solace with his remaining family — descendants of a leading researcher on demonic possession. As her in-laws transform one by one into creatures that feed on fear, she comes to discover that the vows she took in life survive even in death.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/uRxrNXQWkHoENm3nwVOZDYSCx2F.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/biwEwIkjZhMUfXzz59bpeDzwYB6.jpg',
      'ano': 2026,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': 'ff53a1c8-21b1-5fdf-8075-898b7bd2c894',
      'titulo': 'Backrooms',
      'tipo': 'filme',
      'categoria': 'Horror',
      'sinopse': 'A strange doorway appears in the basement of a furniture showroom.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/rhGx6E3qRNMgj3i5su2oukNHwIQ.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/dqmMWNWfLnExDRpMtIMqI97GQFR.jpg',
      'ano': 2026,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': 'a9fd70d4-466d-57da-a776-fd1e18a15c16',
      'titulo': 'Spider-Man',
      'tipo': 'filme',
      'categoria': 'Action',
      'sinopse': 'After being bitten by a genetically altered spider at Oscorp, nerdy but endearing high school student Peter Parker is endowed with amazing powers to become the superhero known as Spider-Man.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/nXdAh5vUwERL4WGVMaee8RoDEAS.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/zQ8AxTPiCiS5nnwXpwTBPBHSaa5.jpg',
      'ano': 2002,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '1a22c4a7-ff83-529b-8045-583bbed8fd51',
      'titulo': 'Scary Movie',
      'tipo': 'filme',
      'categoria': 'Comedy',
      'sinopse': 'Twenty-six years after outrunning a suspiciously familiar masked killer, the Core Four are back in the killer\'s crosshairs and no horror movie IP is safe.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/znHT8peERZRWG1ME3r0Db0EV8k8.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/xWBiXclrRmTggQHMRsIn84YHavs.jpg',
      'ano': 2026,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': 'd9611fa7-cce2-5961-9c54-9d2da05382a9',
      'titulo': 'Avatar Aang: The Last Airbender',
      'tipo': 'filme',
      'categoria': 'Animation',
      'sinopse': 'Avatar Aang, the world\'s last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg',
      'ano': 2026,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '9001462a-fa93-51d8-a4af-12ef00077814',
      'titulo': 'Paradise Hotel',
      'tipo': 'serie',
      'categoria': 'Reality',
      'sinopse': 'Danish version of the reality series "Paradise Hotel".',
      'capa_url': 'https://image.tmdb.org/t/p/w500/ycSBcACecVR0zSnP2ZF83k5f7he.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/nun8Ssmni886Ib4v7chgQbswDfl.jpg',
      'ano': 2005,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': 'ca7a72e5-334b-5cc3-bf16-28b7edde8820',
      'titulo': 'House of the Dragon',
      'tipo': 'serie',
      'categoria': 'Sci-Fi & Fantasy',
      'sinopse': 'The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status',
      'capa_url': 'https://image.tmdb.org/t/p/w500/7V0Ebks0GgpKvQ7QbLAIdX5dos4.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg',
      'ano': 2022,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': 'aa7bf88e-9e30-5d98-b08f-d5311407d661',
      'titulo': 'The Mentalist',
      'tipo': 'serie',
      'categoria': 'Crime',
      'sinopse': 'Patrick Jane, a former celebrity psychic medium, uses his razor sharp skills of observation and expertise at "reading" people to solve serious crimes with the California Bureau of Investigation.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/acYXu4KaDj1NIkMgObnhe4C4a0T.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/q3pCsNvJ7CmdJUz2sJEEUY3pOPC.jpg',
      'ano': 2008,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 16,
      'popularidade': 100,
    },
    {
      'id': 'a02e9b8e-b626-5be0-b6c5-0a5f271393db',
      'titulo': 'Secret Mission - Undercover Agents Never Back Down!',
      'tipo': 'serie',
      'categoria': 'Animation',
      'sinopse': 'Narcotics Enforcement Agent Riko Ikazuchi is undercover with her junior colleague Noma in an apartment that serves as the hideout for a criminal organization. Despite Riko and Noma posing as a newlywed couple, the criminals begin to suspect them after not hearing any marital intimacy during the night. To convince them that they are a loving couple, Noma starts touching Riko\'s body...',
      'capa_url': 'https://image.tmdb.org/t/p/w500/xZV8e1iKi85PFZlbQBdznvtpAVJ.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/5IBSPGPAEFEkEJo4leqvpq0RcKf.jpg',
      'ano': 2023,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '0ecf78a2-1c74-520a-baad-6ba80fff1372',
      'titulo': 'Lioness',
      'tipo': 'serie',
      'categoria': 'Drama',
      'sinopse': 'Cruz Manuelos, a rough-around-the-edges but passionate young Marine, is recruited to join the CIA\'s Lioness Engagement Team to help bring down a terrorist organization from within. Joe, the station chief of the Lioness program, is tasked with training, managing and leading her female undercover operatives.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/rzpHPSEgPTpRs8EHbygwsOw7jC0.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/4NBYDOnEjAzyuP7CMkD5s7fs44K.jpg',
      'ano': 2023,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '2ea31817-098b-54b3-8580-497f8bac56d3',
      'titulo': 'Law & Order: Special Victims Unit',
      'tipo': 'serie',
      'categoria': 'Crime',
      'sinopse': 'In the criminal justice system, sexually-based offenses are considered especially heinous. In New York City, the dedicated detectives who investigate these vicious felonies are members of an elite squad known as the Special Victims Unit. These are their stories.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/iofokHZoUB4Qhik4PflvJl8TT6a.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/obtdxPgmfykYwVnvuYXC5f2xKlQ.jpg',
      'ano': 1999,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 16,
      'popularidade': 100,
    },
    {
      'id': '65fddb97-7b6d-5e3a-8d7d-f35b246404e9',
      'titulo': 'The Rookie',
      'tipo': 'serie',
      'categoria': 'Crime',
      'sinopse': 'Starting over isn\'t easy, especially for small-town guy John Nolan who, after a life-altering incident, is pursuing his dream of being an LAPD officer. As the force\'s oldest rookie, he\'s met with skepticism from some higher-ups who see him as just a walking midlife crisis.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/70kTz0OmjjZe7zHvIDrq2iKW7PJ.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/6iNWfGVCEfASDdlNb05TP5nG0ll.jpg',
      'ano': 2018,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 16,
      'popularidade': 100,
    },
    {
      'id': '473bb0fc-9168-58c8-98c5-073454b474e2',
      'titulo': 'Grey\'s Anatomy',
      'tipo': 'serie',
      'categoria': 'Drama',
      'sinopse': 'Follows the personal and professional lives of a group of doctors at Seattle\'s Grey Sloan Memorial Hospital.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/hjJkrLXhWvGHpLeLBDFznpBTY1S.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/jP0Rhj9OTPDAwQlHQwOLFDdeE8t.jpg',
      'ano': 2005,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '42726974-b3c5-5c3b-bfd7-f7eae7479045',
      'titulo': 'Silo',
      'tipo': 'serie',
      'categoria': 'Sci-Fi & Fantasy',
      'sinopse': 'In a ruined and toxic future, thousands live in a giant silo deep underground. After its sheriff breaks a cardinal rule and residents die mysteriously, engineer Juliette starts to uncover shocking secrets and the truth about the silo.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/gMYZZvnkVNTqSVnVCphWbPXwWwb.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/uTWhbLc7Bj4qNSdW3ZvZKL8cOHv.jpg',
      'ano': 2023,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': 'b51e0f44-46f2-519b-a469-a2d8385871da',
      'titulo': 'Miraculous: Tales of Ladybug & Cat Noir',
      'tipo': 'serie',
      'categoria': 'Action & Adventure',
      'sinopse': 'Marinette and Adrien, two Parisian teenagers, are entrusted with powerful jewels in order to transform into superheroes Ladybug and Cat Noir. But neither hero knows the other\'s true identity — or that they\'re classmates!',
      'capa_url': 'https://image.tmdb.org/t/p/w500/acrtAy8gmxcsEvrDP09MpMSCeDZ.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/lH22EnM0ofC7GsVGU8dAA2RXV1c.jpg',
      'ano': 2015,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '0d7dbaa2-c66e-5ae5-95dd-ae2c1aae6518',
      'titulo': 'Law & Order',
      'tipo': 'serie',
      'categoria': 'Crime',
      'sinopse': 'In cases ripped from the headlines, police investigate serious and often deadly crimes, weighing the evidence and questioning the suspects until someone is taken into custody. The district attorney\'s office then builds a case to convict the perpetrator by proving the person guilty beyond a reasonable doubt. Working together, these expert teams navigate all sides of the complex criminal justice sys',
      'capa_url': 'https://image.tmdb.org/t/p/w500/haJ9eHytVO3H3JooMJG1DiWwDNm.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/tc7canPSAn2X14hYi6Rl3gZm1o4.jpg',
      'ano': 1990,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 16,
      'popularidade': 100,
    },
    {
      'id': '2fde5532-9d7d-5679-86b4-e830c5ae415c',
      'titulo': 'Rick and Morty',
      'tipo': 'serie',
      'categoria': 'Animation',
      'sinopse': 'Follows a sociopathic genius scientist who drags his inherently timid grandson on adventures across the universe.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/owhkU6KRqdXoUQpjV8uyZGPtX58.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/iFOkrSrJRwE27PwbyQeYLlMJXzw.jpg',
      'ano': 2013,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': 'c3d07a8a-7f9e-5421-a470-75367617d2dc',
      'titulo': 'Supernatural',
      'tipo': 'serie',
      'categoria': 'Drama',
      'sinopse': 'When they were boys, Sam and Dean Winchester lost their mother to a mysterious and demonic supernatural force. Subsequently, their father raised them to be soldiers. He taught them about the paranormal evil that lives in the dark corners and on the back roads of America ... and he taught them how to kill it. Now, the Winchester brothers crisscross the country in their \'67 Chevy Impala, battling ev',
      'capa_url': 'https://image.tmdb.org/t/p/w500/8iixmfGx5EIFPdpNvB2JvI3VIqX.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/ro0tlgnsco4SwbdAgmscLkSlMSL.jpg',
      'ano': 2005,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': 'ba8a596d-8c48-5742-aa05-a0ad99044c24',
      'titulo': 'NCIS',
      'tipo': 'serie',
      'categoria': 'Crime',
      'sinopse': 'From murder and espionage to terrorism and stolen submarines, a team of special agents investigates any crime that has any connection to Navy and Marine Corps personnel, regardless of rank or position.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/mBcu8d6x6zB1el3MPNl7cZQEQ31.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/nn3SuLTO4hum8yAxaY4ql8h6kRk.jpg',
      'ano': 2003,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 16,
      'popularidade': 100,
    },
    {
      'id': 'ab620f5c-9793-5b58-9f7e-4c628fa20ef1',
      'titulo': 'The Simpsons',
      'tipo': 'serie',
      'categoria': 'Animation',
      'sinopse': 'Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, medi',
      'capa_url': 'https://image.tmdb.org/t/p/w500/uWpG7GqfKGQqX4YMAo3nv5OrglV.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/jIArNHIekrCSVgdMbKPAXpPY03Y.jpg',
      'ano': 1989,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '459aae27-e35a-5db2-b60f-11b53fb9b35b',
      'titulo': 'Family Guy',
      'tipo': 'serie',
      'categoria': 'Animation',
      'sinopse': 'Sick, twisted, politically incorrect and Freakin\' Sweet animated series featuring the adventures of the dysfunctional Griffin family. Bumbling Peter and long-suffering Lois have three kids. Stewie (a brilliant but sadistic baby bent on killing his mother and taking over the world), Meg (the oldest, and is the most unpopular girl in town) and Chris (the middle kid, he\'s not very bright but has a pa',
      'capa_url': 'https://image.tmdb.org/t/p/w500/3PFsEuAiyLkWsP4GG6dIV37Q6gu.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/l7wShoIdIUwaDIbsHno9pO5MZXT.jpg',
      'ano': 1999,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': 'b0531005-d612-5466-a715-65b2dd3e1d2e',
      'titulo': 'FROM',
      'tipo': 'serie',
      'categoria': 'Mystery',
      'sinopse': 'Unravel the mystery of a nightmarish town in middle America that traps all those who enter. As the unwilling residents fight to keep a sense of normalcy and search for a way out, they must also survive the threats of the surrounding forest – including the terrifying creatures that come out when the sun goes down.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/pRtJagIxpfODzzb0T0NAvZSzErC.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/xLdw1xdHocKYFFvx7w41NchXMfJ.jpg',
      'ano': 2022,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '5e66ba26-369b-579e-823f-7fd1f814c203',
      'titulo': 'Watch What Happens Live with Andy Cohen',
      'tipo': 'serie',
      'categoria': 'Talk',
      'sinopse': 'Bravo network executive Andy Cohen discusses pop culture topics with celebrities and reality show personalities.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/onSD9UXfJwrMXWhq7UY7hGF2S1h.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/hINekSpbcBxjnjGqmIm6I4bz2ab.jpg',
      'ano': 2009,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': 'a9e03c14-984e-5ff5-98dd-78f4d14f8d1a',
      'titulo': 'Quiet Please!',
      'tipo': 'dorama',
      'categoria': 'Comedy',
      'sinopse': 'One month into living on his own, Yi-hyuk was hoping for an exciting, dramatic start to his independent life—but not this kind of drama. What he doesn’t expect is to be tormented by the thunderous noise coming from the apartment next door. Determined to put an end to it, he confronts his neighbor—only to make things infinitely worse when he accidentally punches him in the face.Yi-hyuk tries everyt',
      'capa_url': 'https://image.tmdb.org/t/p/w500/hF9WdEMmEndkkBpOGSzez6Adjdw.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/ihE0jp6V7R6dMwV7YrbYyjdQMvr.jpg',
      'ano': 2025,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': 'ff13253d-9e5b-54eb-877f-483aa53a1bb1',
      'titulo': 'Running Man',
      'tipo': 'dorama',
      'categoria': 'Comedy',
      'sinopse': 'These days, as variety shows are gradually disappearing, this is one of Korea’s representative variety shows that has been responsible for Sunday evenings for over 10 years. This program features numerous stars and members going around various places, playing games, and completing missions. In particular, among the many fun elements of variety shows, this one focuses solely on laughter. Open your',
      'capa_url': 'https://image.tmdb.org/t/p/w500/2Wmmu1MkqxJ48J7aySET9EKEjXz.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/wsHj4oHQJoe7DMYaqNFwVoyLiAh.jpg',
      'ano': 2010,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '1020ee25-9fa3-5f6b-bab5-27dfa1b4c1c1',
      'titulo': 'Our Sticky Love',
      'tipo': 'dorama',
      'categoria': 'Drama',
      'sinopse': 'An ambitious prosecutor loses her memory and moves in with a boxing coach who claims to be her boyfriend. Can this sticky situation turn into real love?',
      'capa_url': 'https://image.tmdb.org/t/p/w500/tSZ4aFpTGc8Oj52SuzPUUZ7WKL0.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/mp2AFsWsuyxCzenJh3DTKw7z4jG.jpg',
      'ano': 2026,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 100,
    },
    {
      'id': '7ada7fba-3dc4-5792-9f4c-c4597174bfec',
      'titulo': 'A Shop for Killers',
      'tipo': 'dorama',
      'categoria': 'Drama',
      'sinopse': 'A niece who lost her parents and grew up in the hands of an uncle who runs a shopping mall faces a new truth after her uncle\'s sudden death.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/7yUY1HUyQuybbvkAAhLzQ7x1l9g.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/mWVeYmtCfA3zvSeZtW5bN2Khe01.jpg',
      'ano': 2024,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 81,
    },
    {
      'id': 'f9e893e5-786d-5c2d-b176-b34c47fa2331',
      'titulo': '물가의 밤',
      'tipo': 'dorama',
      'categoria': 'Animation',
      'sinopse': '',
      'capa_url': 'https://image.tmdb.org/t/p/w500/ooQPZ62APeKooyn5aYkJ7DA3gLh.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/lWDXeRzYlHbJLPeJFCR7glCs1H.jpg',
      'ano': 0,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 72,
    },
    {
      'id': 'f42635b0-2e9d-544d-bdd0-6afc5801057c',
      'titulo': 'Teach You a Lesson',
      'tipo': 'dorama',
      'categoria': 'Action & Adventure',
      'sinopse': 'An inspector from the Educational Rights Protection Bureau (ERPB) who is authorized by the government to use physical intervention and unconventional methods to discipline delinquent students and reform the educational system.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/fMECSPrTmRClSViMsXFYmiYIcWP.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/vyG93jhmPL7tBIhRtCLa5mdBKob.jpg',
      'ano': 2026,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 73,
    },
    {
      'id': '0c45b848-7c61-504f-8c61-b9bc78ed2f8d',
      'titulo': 'Agent Kim Reactivated',
      'tipo': 'dorama',
      'categoria': 'Action & Adventure',
      'sinopse': 'When an unassuming dad\'s daughter goes missing, he dusts off his old black-ops skills to track her down — only to attract the wrong kind of attention.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/mxa7YxVln3Rwnd2Va82PoclTznj.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/g1LJLlmWP74zv9yXKEXm7g9p10O.jpg',
      'ano': 2026,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 71,
    },
    {
      'id': '9eb0719d-b4e7-5966-9d87-133b83b3fe03',
      'titulo': 'Men on a Mission',
      'tipo': 'dorama',
      'categoria': 'Reality',
      'sinopse': 'Male celebs play make-believe as high schoolers, welcoming star transfer students every week and engaging in battles of witty humor and slapstick.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/2jIi55JtYKJTL1km8qHMuUilOWo.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/a8a8z4aJr40zYgRMfmSESppX2eO.jpg',
      'ano': 2015,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 65,
    },
    {
      'id': '64d339aa-a142-59d2-a54e-71d0afa63bad',
      'titulo': 'Infinite Challenge',
      'tipo': 'dorama',
      'categoria': 'Reality',
      'sinopse': 'Infinite Challenge has been reported as the first "Real-Variety" show in Korean television history. The program is largely unscripted, and follows a similar format of challenge-based Reality Television programs, familiar to the audiences in the West, but the challenges are often silly, absurd, or impossible to achieve, so the program takes on the aspect of a satirical comedy variety show, rather t',
      'capa_url': 'https://image.tmdb.org/t/p/w500/3ZIPTvMnzI5ThmdGeEYQFxJV5Sg.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/s2qJb1FLwp1Mse9lY08JqgMp0kw.jpg',
      'ano': 2005,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 55,
    },
    {
      'id': '341930ab-02f4-57d3-8c20-3eb28ef9c429',
      'titulo': 'Squid Game',
      'tipo': 'dorama',
      'categoria': 'Action & Adventure',
      'sinopse': 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits — with deadly high stakes.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/2meX1nMdScFOoV4370rqHWKmXhY.jpg',
      'ano': 2021,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 53,
    },
    {
      'id': '10e9938f-de80-5e6b-b419-06fa9543318e',
      'titulo': 'Weak Hero',
      'tipo': 'dorama',
      'categoria': 'Action & Adventure',
      'sinopse': 'With the aid of unexpected friends, a gifted but introverted student confronts bullies and violent foes — unaware of how dangerous his world will become.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/5Sd01WeraL2oA3Vv6O4rcRxockn.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/q5mJ4oKfGc6Cr9reIHFzD0pQzre.jpg',
      'ano': 2022,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 50,
    },
    {
      'id': 'efaf71ef-3b60-57b7-b164-8a355210a220',
      'titulo': 'Home Alone',
      'tipo': 'dorama',
      'categoria': 'Reality',
      'sinopse': 'It can be a badge of honor to be “single.” “I Live Alone” is a documentary-style South Korean reality series that follows the members of a self-formed club called Rainbow, which is comprised of celebrities who are single and live alone.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/1hqGagr94soBq70Lq7tPHvNmmxy.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/sztoil0XfQ0cSHy4PXmYW6uAdfQ.jpg',
      'ano': 2013,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 45,
    },
    {
      'id': '47502434-53cf-5c2a-a6f3-f22fd8fb2941',
      'titulo': 'Super Wings',
      'tipo': 'dorama',
      'categoria': 'Animation',
      'sinopse': 'An action-packed preschool series about an adorable jet plane named Jett who travels the world delivering packages to children. On every delivery, Jett encounters a new problem that the he and his friends the Super Wings must work together to solve!',
      'capa_url': 'https://image.tmdb.org/t/p/w500/lu2DNsIQgn1Jb6djHvrqJSUQXXl.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/vwgC68MFTgrLaTBaXFnsVAb6y1W.jpg',
      'ano': 2014,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 46,
    },
    {
      'id': 'e5b515f2-1050-537d-9366-20bf633467ec',
      'titulo': '2 Days and 1 Night',
      'tipo': 'dorama',
      'categoria': 'Comedy',
      'sinopse': '2 Days & 1 Night is a South Korean reality-variety show with the motto "real wild road variety." Its main concept is to recommend various places of interest that viewers can visit in South Korea.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/qezeCEkIKHQM5iwyVeYBuXmYA2h.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/32iRX9xqNH3ErJN6FowxdtgYmiY.jpg',
      'ano': 2007,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 48,
    },
    {
      'id': '7b217bba-5af8-5582-b530-499e7eb32a20',
      'titulo': 'Spooky in Love',
      'tipo': 'dorama',
      'categoria': 'Comedy',
      'sinopse': 'When a ghost-seeing heir and an ace prosecutor learn that a single touch makes them a strangely effective duo, they team up to crack unsolved murders.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/acVOH8Pr5LEZ7WKZCbzwNuHVr9x.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/p9tpGftvG18M5y5wsBmPrQpVBsd.jpg',
      'ano': 2026,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 47,
    },
    {
      'id': 'd2df798c-55a7-58fc-ac2f-d16aa372f2fb',
      'titulo': 'My Bias, My Boss',
      'tipo': 'dorama',
      'categoria': 'Comedy',
      'sinopse': 'A dedicated fangirl lands a job at a fashion company, only to discover it was co-founded by her ultimate idol. Determined to remain professional, she hides her identity, but is quickly thrown off course by the company\'s workaholic CEO. As secret unrequited feelings and hidden personal struggles entangle the trio, she finds herself torn between her lifelong obsession and an unexpected new connectio',
      'capa_url': 'https://image.tmdb.org/t/p/w500/A4Y4xlDHS4xi2WI9265vRyIYLoo.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/eBD46F44qKGPZiRLffO4q3JF8Hc.jpg',
      'ano': 2026,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 44,
    },
    {
      'id': 'aeeb257a-904e-5a1c-88c9-27b08c198e63',
      'titulo': 'Dream to You',
      'tipo': 'dorama',
      'categoria': 'Drama',
      'sinopse': 'Dreaming of filmmaking, a passionate high schooler pushes aside all obligations to create short films, inspiring a studious but passionless classmate. Their deep bond eventually turns romantic, but they are abruptly separated when he is forced to move overseas. Years later in their thirties, their lives have completely swapped: she is a disillusioned, struggling TV reporter, while he has become an',
      'capa_url': 'https://image.tmdb.org/t/p/w500/cBiwrUwUNNYXTc5xrDEQWcMqftd.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/5AhL7NKa8UC6QOyzKiDohUM9VYT.jpg',
      'ano': 2026,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 45,
    },
    {
      'id': '524d02ab-a043-5385-bb39-f6238432caa9',
      'titulo': 'Amazing Saturday',
      'tipo': 'dorama',
      'categoria': 'Comedy',
      'sinopse': 'A group of hungry celebrities listen to poppin’ tunes, from recent hits to all-time-favorites, to correctly dictate a part of the lyrics. The songs may sound familiar, but the part they must dictate are unclear to the naked ear, as the lyrics are slurred, muffled by strong beats, etc. If they get the lyrics right, they get to share exquisite regional dishes. But if they get them wrong, a profess',
      'capa_url': 'https://image.tmdb.org/t/p/w500/nEwybsfZBSPjcZamPpKDTaTI5g.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/pNdUVPm6RwvG9Ycd2cuYpLbM7lk.jpg',
      'ano': 2018,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 39,
    },
    {
      'id': '8c9d66e9-583c-5869-97ab-2759246892ed',
      'titulo': 'Law of the Jungle',
      'tipo': 'dorama',
      'categoria': 'Reality',
      'sinopse': 'Law of the Jungle is a hybrid reality show combining elements of drama and documentary. The show is hosted by comedian Kim Byung Man, and each episode invites various celebrities from the various field. So far, many of idol stars and famous actors have appeared on the show. The show introduces viewers to exotic locations around the world where celebrities must work together in order to complete mi',
      'capa_url': 'https://image.tmdb.org/t/p/w500/zgMOq3H27nYikqjykeXCIIFRbjK.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/sgE2evtpaP5b9tavrgYCy2nKYLT.jpg',
      'ano': 2011,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 39,
    },
    {
      'id': '619b7fc8-1061-5c56-865a-9751de29980b',
      'titulo': 'Tomb Raider King',
      'tipo': 'dorama',
      'categoria': 'Animation',
      'sinopse': 'Chaos ensues overnight when mysterious tombs suddenly surface, filled with divine relics granting overwhelming power, triggering a global power struggle to claim them for dominion. Among the havoc, a raider, Jooheon Suh, is betrayed and left for dead until a second chance brings him back years before the relics. Fueled by fury and future knowledge, he sets out to raid each tomb before they arise.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/xDW6cor12UD0b2IqboQWnrIn0UO.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w1280/irM3WhxOorkklhx5To9cfG2ktM6.jpg',
      'ano': 2026,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 12,
      'popularidade': 41,
    },
    {
      'id': '4d50df9d-6edd-51b3-809d-3355caa71a2e',
      'titulo': 'Interestelar',
      'tipo': 'filme',
      'categoria': 'Ficção Científica',
      'sinopse': 'A exploração de buracos de minhoca em busca de um novo lar para a humanidade.',
      'capa_url': 'https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
      'banner_url': 'https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
      'ano': 2014,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 10,
      'popularidade': 92,
    },
    {
      'id': 'fb44379f-a829-55af-a436-fa58c852e4ba',
      'titulo': 'Breaking Bad',
      'tipo': 'serie',
      'categoria': 'Drama',
      'sinopse': 'Um professor de química vira produtor de metanfetamina.',
      'capa_url': 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
      'banner_url': 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
      'ano': 2008,
      'idioma_tipo': 'LEG',
      'classificacao_etaria': 16,
      'popularidade': 95,
    },
    {
      'id': 'a0298033-d081-57b1-97e3-da63ae8f1b94',
      'titulo': 'Vagabond',
      'tipo': 'dorama',
      'categoria': 'Ação',
      'sinopse': 'Um homem investiga a queda de um avião que envolve seu sobrinho.',
      'capa_url': 'https://static.tvmaze.com/uploads/images/original_untouched/211/529234.jpg',
      'banner_url': 'https://static.tvmaze.com/uploads/images/original_untouched/211/529234.jpg',
      'ano': 2019,
      'idioma_tipo': 'DUAL',
      'classificacao_etaria': 16,
      'popularidade': 88,
    },
    {
      'id': 'b3c70da3-cb00-5520-bdfe-39b5cd6a1d28',
      'titulo': 'O Rei Leão',
      'tipo': 'filme',
      'categoria': 'Animação',
      'sinopse': 'Um leãozinho herdeiro do trono foge de casa.',
      'capa_url': 'https://m.media-amazon.com/images/M/MV5BZGRiZDZhZjItM2M3ZC00Y2IyLTk3Y2MtMWY5YjliNDFkZTJlXkEyXkFqcGc@._V1_SX300.jpg',
      'banner_url': 'https://m.media-amazon.com/images/M/MV5BZGRiZDZhZjItM2M3ZC00Y2IyLTk3Y2MtMWY5YjliNDFkZTJlXkEyXkFqcGc@._V1_SX300.jpg',
      'ano': 1994,
      'idioma_tipo': 'DUB',
      'classificacao_etaria': 0,
      'popularidade': 85,
    },
  ];

  @override
  Future<List<Midia>> fetchMidias() async {
    await Future<void>.delayed(const Duration(milliseconds: 200));
    return _seed.map(Midia.fromJson).toList();
  }

  @override
  Future<List<Midia>> fetchMidiasPorTipo(String tipo) async {
    await Future<void>.delayed(const Duration(milliseconds: 200));
    return _seed
        .where((m) => m['tipo'] == tipo)
        .map(Midia.fromJson)
        .toList();
  }
}
