"""validar_idioma.py — Valida se um texto está em Português do Brasil (pt-BR).

Uso:
  python scripts/validar_idioma.py "texto a validar"
  echo "texto" | python scripts/validar_idioma.py --stdin

Exit: 0 = pt-BR, 1 = não-pt-BR, 2 = erro
"""
import re
import sys

# Palavras comuns em português (artigos, preposições, conjunções, pronomes, verbos, técnicos)
PALAVRAS_PT = {
    # Artigos
    "o", "a", "os", "as", "um", "uma", "uns", "umas",
    # Preposições
    "de", "do", "da", "dos", "das", "em", "no", "na", "nos", "nas",
    "por", "para", "com", "sem", "sob", "entre", "até", "desde",
    "após", "antes", "durante", "contra", "perante", "trás",
    "num", "nuns", "numa", "numas",  # contrações
    # Conjunções
    "e", "ou", "mas", "porém", "contudo", "todavia", "entretanto",
    "que", "se", "pois", "porque", "como", "quando", "onde",
    "logo", "assim", "então", "portanto", "pois", "porquanto",
    # Pronomes
    "eu", "tu", "ele", "ela", "nós", "vocês", "eles", "elas",
    "me", "te", "se", "nos", "vos", "meu", "teu", "seu", "sua",
    "nosso", "nosso", "você", "você", "mim", "ti", "si",
    # Verbos comuns (infinitivo e conjugados)
    "é", "está", "são", "tem", "pode", "deve", "fazer", "dizer",
    "ir", "vir", "dar", "ver", "saber", "querer", "poder",
    "ter", "ser", "estar", "haver", "ficar", "trazer", "levar",
    "foi", "era", "vai", "vem", "dá", "vê", "sabe", "quer",
    "fez", "disse", "veio", "deu", "vi", "sei", "quis",
    "estava", "estavam", "tinha", "tinham", "podia", "podiam",
    "devia", "devam", "faça", "façam", "diga", "digam",
    "exibe", "exibem", "exibiu", "exibir",
    "mostra", "mostram", "mostrou", "mostrar",
    "identificar", "identifica", "identificou", "identifique",
    "verificar", "verifica", "verificou", "verifique",
    "investigar", "investiga", "investigou", "investigue",
    "aparece", "aparecem", "apareceu", "aparecer",
    "funciona", "funcionam", "funcionou", "funcionar",
    "rodando", "roda", "rode",
    "parar", "para", "parou", "pare",
    "reiniciar", "reinicia", "reiniciou", "reiniciar",
    "conectar", "conecta", "conectou", "conectar",
    # Termos técnicos comuns em pt-BR
    "widget", "toast", "erro", "erros", "falha", "falhas",
    "log", "logs", "debug", "debugar",
    "conexão", "conexao", "rede", "servidor", "cliente",
    "banco", "dados", "tabela", "query", "sql",
    "arquivo", "arquivos", "pasta", "pastas",
    "config", "configuração", "configuracao", "configurar",
    "script", "scripts", "código", "codigo", "programa",
    "tela", "janela", "botão", "botao", "clique", "clicar",
    "mouse", "teclado", "tecla", "enter", "escape",
    "audio", "som", "voz", "fala", "falar", "fala",
    "microfone", "microphone", "speaker", "speaker",
    "volume", "mudo", "mutado", "unmute",
    "notificação", "notificacao", "alert", "alerta",
    "janela", "abas", "tab", "abas",
    "menu", "menus", "opção", "opcao", "opções", "opcoes",
    "item", "itens", "lista", "listas", "item",
    "salvar", "salva", "salvou", "save",
    "carregar", "carrega", "carregou", "load",
    "abrir", "abre", "abriu", "open",
    "fechar", "fecha", "fechou", "close",
    "minimizar", "minimiza", "minimizou",
    "maximizar", "maximiza", "maximizou",
    "restaurar", "restaura", "restaurou",
    # Adjetivos/advérbios comuns
    "bom", "mau", "grande", "pequeno", "novo", "velho",
    "muito", "pouco", "mais", "menos", "também", "já",
    "agora", "hoje", "amanhã", "ontem", "sempre", "nunca",
    "aqui", "ali", "lá", "cá", "longe", "perto",
    "bem", "mal", "melhor", "pior", "certo", "errado",
    "pronto", "prontos", "feito", "feitos",
    "mesmo", "mesma", "mesmos", "mesmas",
    "outro", "outra", "outros", "outras",
    "tal", "tais", "talvez", "provavelmente",
    # Números/quantificadores
    "um", "dois", "três", "quatro", "cinco", "muita", "muitos",
    "poucos", "pouca", "todos", "todas", "cada", "qualquer",
    "vários", "varias", "alguns", "algumas",
    # Expressões
    "não", "sim", "obrigado", "por favor", "desculpe",
    "obrigada", "valeu", "legal", "certo", "exato",
    "claro", "clara", "óbvio", "obvio", "natural",
    "entendi", "entendido", "compreendi", "entender",
    # Preposições extras
    "por", "para", "com", "sem", "sob", "entre", "até", "desde",
    "após", "antes", "durante", "contra", "perante", "trás",
    "num", "nuns", "numa", "numas",
    # Conjunções extras
    "e", "ou", "mas", "porém", "contudo", "todavia", "entretanto",
    "que", "se", "pois", "porque", "como", "quando", "onde",
    "logo", "assim", "então", "portanto", "pois", "porquanto",
    # Pronomes extras
    "eu", "tu", "ele", "ela", "nós", "vocês", "eles", "elas",
    "me", "te", "se", "nos", "vos", "meu", "teu", "seu", "sua",
    "nosso", "nosso", "você", "você", "mim", "ti", "si",
    # Verbos extras
    "é", "está", "são", "tem", "pode", "deve", "fazer", "dizer",
    "ir", "vir", "dar", "ver", "saber", "querer", "poder",
    "ter", "ser", "estar", "haver", "ficar", "trazer", "levar",
    "foi", "era", "vai", "vem", "dá", "vê", "sabe", "quer",
    "fez", "disse", "veio", "deu", "vi", "sei", "quis",
    "estava", "estavam", "tinha", "tinham", "podia", "podiam",
    "devia", "devam", "faça", "façam", "diga", "digam",
    # Adjetivos/advérbios comuns
    "bom", "mau", "grande", "pequeno", "novo", "velho",
    "muito", "pouco", "mais", "menos", "também", "já",
    "agora", "hoje", "amanhã", "ontem", "sempre", "nunca",
    "aqui", "ali", "lá", "cá", "longe", "perto",
    "bem", "mal", "melhor", "pior", "certo", "errado",
    "pronto", "prontos", "feito", "feitos",
    "mesmo", "mesma", "mesmos", "mesmas",
    "outro", "outra", "outros", "outras",
    "tal", "tais", "talvez", "provavelmente",
    # Números/quantificadores
    "um", "dois", "três", "quatro", "cinco", "muita", "muitos",
    "poucos", "pouca", "todos", "todas", "cada", "qualquer",
    "vários", "varias", "alguns", "algumas",
    # Expressões
    "não", "sim", "obrigado", "por favor", "desculpe",
    "obrigada", "valeu", "legal", "certo", "exato",
    "claro", "clara", "óbvio", "obvio", "natural",
    "entendi", "entendido", "compreendi", "entender",
    # Termos técnicos
    "widget", "toast", "erro", "erros", "falha", "falhas",
    "log", "logs", "debug", "debugar",
    "conexão", "conexao", "rede", "servidor", "cliente",
    "banco", "dados", "tabela", "query", "sql",
    "arquivo", "arquivos", "pasta", "pastas",
    "config", "configuração", "configuracao", "configurar",
    "script", "scripts", "código", "codigo", "programa",
    "tela", "janela", "botão", "botao", "clique", "clicar",
    "mouse", "teclado", "tecla", "enter", "escape",
    "audio", "som", "voz", "fala", "falar", "fala",
    "microfone", "microphone", "speaker", "speaker",
    "volume", "mudo", "mutado", "unmute",
    "notificação", "notificacao", "alert", "alerta",
    "janela", "abas", "tab", "abas",
    "menu", "menus", "opção", "opcao", "opções", "opcoes",
    "item", "itens", "lista", "listas", "item",
    "salvar", "salva", "salvou", "save",
    "carregar", "carrega", "carregou", "load",
    "abrir", "abre", "abriu", "open",
    "fechar", "fecha", "fechou", "close",
    "minimizar", "minimiza", "minimizou",
    "maximizar", "maximiza", "maximizou",
    "restaurar", "restaura", "restaurou",
    "exibe", "exibem", "exibiu", "exibir",
    "mostra", "mostram", "mostrou", "mostrar",
    "identificar", "identifica", "identificou", "identifique",
    "verificar", "verifica", "verificou", "verifique",
    "investigar", "investiga", "investigou", "investigue",
    "aparece", "aparecem", "apareceu", "aparecer",
    "funciona", "funcionam", "funcionou", "funcionar",
    "rodando", "roda", "rode",
    "parar", "para", "parou", "pare",
    "reiniciar", "reinicia", "reiniciou", "reiniciar",
    "conectar", "conecta", "conectou", "conectar",
    # Adjetivos/advérbios comuns
    "bom", "mau", "grande", "pequeno", "novo", "velho",
    "muito", "pouco", "mais", "menos", "também", "já",
    "agora", "hoje", "amanhã", "ontem", "sempre", "nunca",
    "aqui", "ali", "lá", "cá", "longe", "perto",
    "bem", "mal", "melhor", "pior", "certo", "errado",
    "pronto", "prontos", "feito", "feitos",
    "mesmo", "mesma", "mesmos", "mesmas",
    "outro", "outra", "outros", "outras",
    "tal", "tais", "talvez", "provavelmente",
    # Números/quantificadores
    "um", "dois", "três", "quatro", "cinco", "muita", "muitos",
    "poucos", "pouca", "todos", "todas", "cada", "qualquer",
    "vários", "varias", "alguns", "algumas",
    # Expressões
    "não", "sim", "obrigado", "por favor", "desculpe",
    "obrigada", "valeu", "legal", "certo", "exato",
    "claro", "clara", "óbvio", "obvio", "natural",
    "entendi", "entendido", "compreendi", "entender",
    # Preposições
    "num", "nuns", "numa", "numas",
    # Contrações
    "pelo", "pela", "pelos", "pelas",
    "pelo", "pela", "pelos", "pelas",
    # Verbos de ação
    "rodar", "roda", "rodou", "rodar",
    "executar", "executa", "executou",
    "processar", "processa", "processou",
    "analisar", "analisa", "analisou",
    "monitorar", "monitora", "monitorou",
    "detectar", "detecta", "detectou",
    "corrigir", "corrige", "corrigiu",
    "resolver", "resolve", "resolveu",
    "testar", "testa", "testou",
    "validar", "valida", "validou",
    "compilar", "compila", "compilou",
    "instalar", "instala", "instalou",
    "atualizar", "atualiza", "atualizou",
    # Vocabulário geral básico (correção de falso negativo — dicionário incompleto)
    "sobre", "dia", "hoje", "amanhã", "semana", "ano", "mês", "meses",
    "sistema", "ligado", "contexto", "restaurado", "cinco", "quatro", "cem",
    "cento", "pendências", "fila", "assessor", "credenciado", "informação",
    "recomendação", "pessoal", "geral", "juros", "básicos", "quatorze",
    "cenário", "favorece", "renda", "fixa", "simples", "sugestão", "sensata",
    "aplicar", "título", "bancário", "liquidez", "diária", "pague", "mínimo",
    "índice", "referência", "mercado", "aceito", "bancos", "digitais",
    "comprar", "compra", "fracionada", "público", "acompanha", "esses",
    "tesouro", "permite", "permitem", "seguros", "rendem", "brutos",
    "resgate", "rápido", "sendo", "lúcido", "impostos", "valor", "valores",
    "verdadeiro", "hábito", "guardar", "dinheiro", "todo", "retorno",
    "imediato", "depois", "isto", "sou", "site", "oficial", "real",
    "reais", "menos", "mais", "muito", "pouco", "grande", "pequeno",

    # Corpus do ecossistema (Constituição, AGENTS.md, aprendizados)
    "usuário", "cláusula", "pétrea", "habilidades", "sessão", "memória",
    "áudio", "prioridade", "confiança", "validação", "automaticamente",
    "padrão", "segurança", "comunicação", "máxima", "correção",
    "instrução", "decisão", "constituição", "imutável", "consequências",
    "solução", "automático", "único", "primeiro", "única", "obrigatório",
    "padrões", "execução", "prioritária", "decisões", "alteração",
    "profundidade", "persistência", "evolução", "primeira", "documentação",
    "implementação", "português", "mudança", "violação", "pronúncia",
    "dependências", "confirmação", "saudação", "obrigatória",
    "necessidade", "posteriormente", "tradução", "necessário", "técnicos",
    "resiliência", "conteúdo", "criação", "responsabilidade",
    "integridade", "detecção", "automática", "aplicável", "técnico",
    "sessões", "técnica", "princípio", "compreensão", "integração",
    "possível", "relatório", "formatação", "manualmente", "inglês",
    "regressão", "duplicação", "diagnóstico", "quê", "velocidade",
    "imediatamente", "explícito", "análise", "qualidade", "ambiguidade",
    "máquina", "ação", "sincronização", "próximos", "lição",
    "transparência", "complexidade", "criticidade", "corretamente",
    "ético", "rápida", "cláusulas", "versão", "proteção", "catálogo",
    "explicitamente", "contínua", "somente", "automação", "consistência",
    "silêncio", "operação", "função", "domínio", "evidência", "conclusão",
    "última", "sozinho", "pontuação", "verdade", "cérebro", "contínuo",
    "autenticação", "recuperação", "válido", "serviços", "ausência",
    "habilidade", "exceção", "ativação", "além", "navegação",
    "normalmente", "naturalidade", "necessária", "serviço", "concluída",
    "autorização", "critérios", "disponível", "novamente", "configurações",
    "funções", "próprio", "verificação", "inventário", "atualização",
    "ações", "automáticos", "excessivamente", "saída", "governança",
    "missão", "otimização", "alterações", "mínima", "corrupção",
    "heurísticas", "seção", "física", "restrições", "limitações",
    "continuidade", "negociáveis", "acentuação", "gramática", "soluções",
    "sustentável", "manutenção", "nível", "módulo", "múltiplos",
    "aceitação", "desnecessária", "funcionalidades", "escalabilidade",
    "desnecessárias", "critério", "instalação", "proibição",
    "acessibilidade", "referências", "visível", "estão", "específico",
    "narração", "vírgula", "migração", "confiável", "observabilidade",
    "legibilidade", "interrupção", "mudanças", "legível", "desnecessários",
    "histórico", "terceiros", "permissão", "lições", "mantém", "realidade",
    "explicação", "botões", "atividade", "inferência", "concordância",
    "refatoração", "exclusão", "verificável", "módulos", "crítica",
    "sensíveis", "tecnicamente", "vulnerabilidades", "condições",
    "funcionalidade", "permissões", "concorrência", "inconsistência",
    "reconexão", "métricas", "técnicas", "estática", "máximo",
    "responsável", "redundância", "válida", "substituição", "semântico",
    "memórias", "silenciosamente", "privacidade", "sociedade", "semântica",
    "ambiguidades", "desperdício", "útil", "relatórios", "conexões",
    "monólito", "microserviço", "tópicos", "respiração", "reorganização",
    "hipótese", "órfãos", "início", "compatibilidade", "necessários",
    "pré", "privilégio", "informações", "investigação", "indefinidamente",
    "parcialmente", "números", "normalização", "inteligência", "própria",
    "diretório", "atômica", "prévia", "solicitação", "resolução",
    "repetição", "repositório", "autônomo", "descrição", "árvore",
    "sensação", "brasileiro", "visão", "transcrição", "política",
    "divergência", "têm", "próximas", "viés", "explícita", "áudios",
    "próprios", "geração", "rastreável", "testável", "improvisação",
    "rapidamente", "classificação", "média", "operações", "críticas",
    "responsabilidades", "apresentação", "maneira", "validações",
    "unitários", "indisponível", "sanitização", "exposição", "diretamente",
    "provável", "inspeção", "simplesmente", "capacidade", "lógica",
    "irreversível", "simplicidade", "manutenibilidade", "ambígua",
    "dúvida", "consolidação", "variáveis", "reutilizáveis", "estritamente",
    "episódica", "prioridades", "pétreas", "autoapresentação", "afirmação",
    "ineficiência", "oportunidade", "crítico", "verificações",
    "obrigações", "inicialização", "condição", "capacidades", "retenção",
    "delírio", "fácil", "entregável", "preâmbulos", "utilidade",
    "preferências", "raciocínio", "naturalmente", "gravidade",
    "dicionário", "umidade", "previsão", "saúde", "prático", "prática",
    "balão", "clã", "opacidade", "criticalidade", "sugestões",
    "contrações", "dificuldade", "síntese", "localização", "quantidade",
    "dependência", "semânticos", "reinicialização", "identificação",
    "exatamente", "válidos", "remoção", "espontânea", "brevemente",
    "estratégias", "idade", "expõem", "obrigatórios", "instantânea",
    "exclusivamente", "exclamação", "acadêmico", "variações", "direção",
    "divisão", "posição", "interação", "primário", "latência", "senão",
    "pós", "transcrições", "maiúscula", "feira", "sábado", "pendência",
    "sequência", "estável", "pressão", "conectividade", "heurística",
    "práticas", "inteiro", "irmãos", "inteira", "contém", "obediência",
    "edição", "domínios", "centralidade", "microscópio", "balanço",
    "expõe", "autoridade", "depuração",

    # Meses e dias
    "janeiro", "fevereiro", "março", "abril", "maio", "junho",
    "julho", "agosto", "setembro", "outubro", "novembro", "dezembro",
    "segunda", "terça", "quarta", "quinta", "sexta", "sábado", "domingo",
    "ontem", "amanhã", "madrugada", "manhã", "tarde", "noite", "meianoite",
    # Números por extenso
    "zero", "um", "dois", "três", "quatro", "cinco", "seis", "sete",
    "oito", "nove", "dez", "onze", "doze", "treze", "catorze", "quinze",
    "dezesseis", "dezessete", "dezoito", "dezenove", "vinte", "trinta",
    "quarenta", "cinquenta", "sessenta", "setenta", "oitenta", "noventa",
    "cem", "mil", "milhão", "bilhão", "metade", "terço", "dúzia",
    # Saudações e cortesias
    "oi", "olá", "bom", "boa", "tchau", "até", "obrigado", "obrigada",
    "favor", "desculpa", "desculpe", "abraço", "bem-vindo", "por",
    # Verbos supercomuns
    "vou", "vai", "vamos", "vão", "sou", "era", "fui", "será", "ser",
    "estou", "estava", "estará", "estar", "tenho", "tinha", "terei",
    "quero", "queremos", "podem", "dever", "dar", "dou", "der", "ver",
    "vejo", "viu", "vir", "vem", "vêm", "venha", "sei", "sabe", "sabem",
    "falo", "falou", "falar", "fica", "ficou", "ficar", "acho", "acha",
    "preciso", "precisa", "precisam", "ajuda", "ajudou", "ajudar",
    "uso", "usa", "usado", "usar", "tenta", "tentei", "tentar",
    "gosto", "gosta", "entendi", "entender", "começo", "começar",
    "termino", "terminar", "acabei", "acabar", "posso", "possa",
    "queria", "gostaria", "precisava", "fiz", "fez", "feito",
    "disse", "digo", "dizer", "vi", "vejo", "visto", "olhar", "olhei",
    # Advérbios e conectivos
    "sim", "não", "talvez", "sempre", "nunca", "quase", "bastante",
    "ainda", "já", "também", "só", "apenas", "mesmo", "muito", "pouca",
    "pouco", "bem", "mal", "melhor", "pior", "logo", "cedo", "agora",
    "antes", "aqui", "ali", "lá", "perto", "longe", "dentro", "fora",
    "acima", "abaixo", "embaixo", "frente", "trás", "junto", "juntos",
    "assim", "inclusive", "inclusive", "enquanto", "embora", "porém",
    # Substantivos gerais
    "casa", "carro", "trabalho", "vida", "gente", "pessoa", "pessoas",
    "coisa", "coisas", "hora", "horas", "minuto", "minutos", "mundo",
    "lugar", "vez", "vezes", "forma", "parte", "partes", "nome",
    "exemplo", "tipo", "tipos", "modo", "jeito", "razão", "motivo",
    "fim", "meio", "centro", "lado", "ponto", "pontos", "pergunta",
    "resposta", "ideia", "opinião", "erro", "acerto", "sucesso",
    "fracasso", "tempo", "momento", "instante", "futuro", "passado",
    "presente", "história", "notícia", "notícias", "amigo", "amiga",
    "filho", "filha", "pai", "mãe", "irmão", "irmã", "água", "comida",
    # Dinheiro e finanças
    "conta", "banco", "dinheiro", "preço", "valor", "custo", "lucro",
    "prejuízo", "mercado", "ação", "ações", "título", "renda", "juros",
    "taxa", "investimento", "investir", "investidor", "poupança",
    "risco", "ganho", "perda", "meta", "sonho", "objetivo", "plano",
    "projeto", "tarefa", "resultado", "problema", "solução", "dúvida",
    "carteira", "aporte", "resgate", "liquidez", "imposto", "impostos",
    "selic", "cdi", "cdb", "tesouro", "bolso", "salário", "dívida",
    "pagamento", "compra", "venda", "loja", "cartão", "pix",
    # Adjetivos gerais
    "bom", "boa", "ótimo", "ótima", "ruim", "péssimo", "péssima",
    "novo", "nova", "velho", "antigo", "antiga", "fácil", "difícil",
    "grande", "pequeno", "alto", "baixo", "longo", "curto", "rápido",
    "lento", "forte", "fraco", "rico", "pobre", "feliz", "triste",
    "claro", "escuro", "cheio", "vazio", "quente", "frio", "limpo",
    "sujo", "certo", "errado", "verdadeiro", "falso", "possível",
    "impossível", "simples", "complexo", "importante", "normal",
    "estranho", "bonito", "feio", "barato", "caro", "grátis", "livre",
    "ocupado", "pronto", "primeiro", "segundo", "terceiro", "próprio",
    "igual", "diferente", "melhor", "pior", "último", "próximo",

    # Fontes linguísticas públicas: Wiktionary/OpenSubtitles pt-BR top frequências
    "isso", "tudo", "minha", "quem", "nada", "ao", "há", "pra", "lo",
    "cara", "algo", "esse", "essa", "temos", "deus", "tão", "esta",
    "estamos", "alguém", "senhor", "anos", "este", "sr", "dele", "seus",
    "parece", "aí", "oh", "nem", "homem", "fazendo", "lhe", "faz", "ei",
    "qual", "la", "ninguém", "disso", "comigo", "alguma", "seja", "vá",
    "sinto", "podemos", "suas", "quanto", "nossa", "deixe", "meus",
    "poderia", "ok", "dela", "certeza", "sair", "daqui", "mulher", "toda",
    "merda", "algum", "volta", "espere", "falando", "sabia", "aconteceu",
    "olhe", "diz", "atrás", "voltar", "sério", "tenha", "deveria",
    "realmente", "ah", "seria", "às", "olha", "aquele", "fique", "los",
    "deixar", "amor", "dê", "pensei", "cabeça", "família", "duas",
    "querida", "dias", "indo", "homens", "matar", "nenhum", "precisamos",
    "pegar", "somos", "cidade", "fosse", "amigos", "garota", "deles",
    "medo", "caso", "foram", "importa", "tanto", "porta", "tentando",
    "entrar", "minhas", "amo", "morto", "demais", "aquela", "tá",
    "dizendo", "garoto", "encontrar", "papai", "sorte", "cima", "droga",
    "nisso", "quiser", "morte", "essas", "idéia", "achei", "morrer",
    "espero", "caminho", "polícia", "sente", "arma", "aos", "acabou",
    "quarto", "crianças", "acredito", "espera", "for", "chegar", "cuidado",
    "tive", "pensar", "veja", "mãos", "teve", "consigo", "sido", "contar",
    "chefe", "olhos", "ia", "idiota", "significa", "entendo", "dr",
    "deixa", "vindo", "ouvir", "passar", "acontecendo", "sangue", "mamãe",
    "devo", "esposa", "lembra", "problemas", "jogo", "guerra", "nossos",
    "teria", "mão", "querem", "sra", "pensando", "boca", "coração",
    "escola", "corpo", "conhece", "licença", "nenhuma", "causa", "havia",
    "ouvi", "faço", "terra", "saia", "jack", "tivesse", "porra", "maior",
    "capitão", "matou", "tirar", "querido", "diabos", "senhora", "chance",
    "morreu", "marido", "número", "pegue", "esperar", "conheço",
    "preocupe", "comer", "esperando", "festa", "mulheres", "trabalhar",
    "prazer", "houve", "aquilo", "telefone", "sabemos", "consegue",
    "deixou", "irá", "filhos", "john", "tomar", "conseguir", "esteja",
    "dormir", "desse", "dessa", "pais", "calma", "café", "sentir", "bebê",
    "muitas", "eram", "acontecer", "neste", "chega", "suficiente", "terá",
    "caras", "fale", "nessa", "procurando", "vivo", "acordo", "escute",
    "vendo", "fogo", "chegou", "ouça", "criança", "conseguiu", "viver",
    "jantar", "culpa", "equipe", "achar", "falta", "pensa", "sala",
    "aonde", "desta", "nossas", "certa", "leve", "armas", "puta", "mudar",
    "presidente", "ligar", "louco", "acreditar", "cama", "nesse",
    "conversar", "perder", "pagar", "livro", "faria", "devemos", "existe",
    "trouxe", "ouviu", "alô", "paz", "força", "nele", "direito", "lembro",
    "pena", "dizem", "casamento", "agente", "pedir", "estiver", "palavra",
    "dólares", "entende", "luz", "médico", "pro", "atenção", "volte",
    "música", "final", "país", "filme", "adeus", "próxima", "estes",
    "fazem", "rei", "descobrir", "iria", "acontece", "semanas",
    "brincando", "jovem", "controle", "perguntar", "hospital", "linda",
    "sam", "jesus", "chama", "resto", "jogar", "colocar", "esteve", "fico",
    "rua", "especial", "ai", "chamar", "precisar", "garotas", "negócio",
    "continuar", "rapazes", "vim", "pé", "falei", "pegou", "estado",
    "seguro", "ajude", "tire", "engraçado", "devem", "saiu", "sai",
    "escritório", "encontro", "sinal", "michael", "estas", "começou",
    "daí", "respeito", "prisão", "manter", "incrível", "aqueles", "nesta",
    "ajudá", "srta", "sentido", "deste", "doutor", "passou", "estivesse",
    "perfeito", "escolha", "estávamos", "fiquei", "andar", "pequena",
    "ama", "boas", "mortos", "entendeu", "esqueça", "milhões", "chão",
    "pense", "ar", "acredita", "ganhar", "sexo", "dor", "charlie",
    "trabalhando", "mente", "fato", "cabelo", "las", "olhando", "consegui",
    "policial", "the", "finalmente", "mesa", "linha", "lhes", "frank",
    "abra", "rapaz", "palavras", "cuidar", "anda", "situação", "tom",
    "cale", "disseram", "tua", "conhecer", "assassino", "passa", "lindo",
    "tente", "continue", "estive", "peguei", "casar", "perdeu", "sozinha",
    "avião", "preso", "conosco", "contou", "estás", "lamento", "ficará",
    "grandes", "emprego", "estaria", "odeio", "bonita", "ordem", "local",
    "pediu", "tio", "achou", "olho", "crime", "voltou", "farei", "fizeram",
    "encontrei", "partir", "sol", "soube", "ataque", "viagem", "uh",
    "vontade", "rosto", "chamado", "doente", "foto", "inferno", "hotel",
    "acidente", "tome", "tv", "mensagem", "levou", "david", "grupo",
    "natal", "senhores", "george", "professor", "menina", "melhores",
    "ligue", "caixa", "nave", "general", "perguntas", "exército", "povo",
    "campo", "irei", "continua", "tiver", "voce", "estarei", "aniversário",
    "morta", "guarda", "usando", "levá", "trabalha", "menino", "harry",
    "questão", "porquê", "mike", "meia", "penso", "vale", "área",
    "maldito", "quantos", "leva", "graças", "beber", "namorada",
    "encontrou", "lembrar", "dei", "matá", "companhia", "mestre", "barco",
    "deixá", "céu", "prometo", "ligou", "seguir", "pudesse", "perdi",
    "surpresa", "negócios", "fome", "conversa", "lutar", "diria", "chave",
    "olhada", "dando", "fará", "fotos", "ouvindo", "coloque", "fundo",
    "ler", "governo", "fazê", "adoro", "banheiro", "explicar", "chame",
    "advogado", "totalmente", "juro", "contato", "ficando", "joe",
    "cachorro", "procurar", "traga", "peter", "lei", "segundos",
    "completamente", "apartamento", "saiba", "mandou", "bons", "esquerda",
    "teremos", "fomos", "saindo", "roupa", "carta", "buscar", "espaço",
    "vista", "disto", "parabéns", "naquela", "tocar", "interessante",
    "namorado", "fizemos", "segredo", "tenente", "velha", "assunto",
    "tentou", "senti", "ben", "luta", "passada", "norte", "conte",
    "reunião", "divertido", "roupas", "horrível", "destino", "viva",
    "nela", "garotos", "creio", "depressa", "aposto", "fazemos", "vidas",
    "energia", "costas", "né", "drogas", "papel", "faremos", "direita",
    "mandar", "estrada", "mudou", "tivemos", "hey", "cair", "levante",
    "alma", "parecia", "assassinato", "peça", "coronel", "naquele",
    "loucura", "escuta", "show", "planeta", "maioria", "bar", "puder",
    "sargento", "monte", "ligação", "james", "conheci", "tiro", "contigo",
    "teste", "beleza", "trem", "acredite", "pronta", "lembre", "prova",
    "bola", "fazia", "paul", "socorro", "desses", "regras", "serão",
    "através", "bela", "conhecê", "deixei", "padre", "sul", "duro",
    "igreja", "bebida", "tendo", "humano", "us", "ordens", "ex", "breve",
    "maravilhoso", "escrever", "pega", "toque", "sentar", "jimmy",
    "terrível", "volto", "atirar", "correr", "honra", "queira", "existem",
    "diferença", "chegando", "encontrá", "dito", "pés", "gostar", "carne",
    "saiam", "comando", "parem", "saco", "capaz", "graça", "acham",
    "cerveja", "paciente", "passo", "parecer", "foda", "esquecer",
    "aprender", "entrou", "bob", "fiquem", "conselho", "esperava",
    "devagar", "proteger", "detetive", "começa", "delas", "fugir", "ponha",
    "bater", "time", "encontramos", "perigo", "hein", "propósito",
    "certamente", "cheiro", "branco", "poderá", "gostei", "chamada",
    "louca", "mar", "tens", "fbi", "vítima", "ilha", "perigoso", "caiu",
    "quais", "lugares", "york", "confiar", "rio", "base", "venham",
    "estúpido", "pensou", "vestido", "bomba", "tira", "tempos", "andando",
    "ambos", "dessas", "tony", "belo", "quantas", "diferentes",
    "desculpas", "direto", "sentindo", "pedi", "ouro", "jake", "ligo",
    "últimos", "bill", "tê", "liga", "justo", "cavalo", "mate", "mantenha",
    "esqueci", "serei", "senhoras", "jamais", "deveríamos", "relação",
    "doce", "cadê", "acaba", "mostre", "alex", "deixem", "vermelho",
    "lixo", "conseguimos", "sonhos", "dormindo", "cristo", "corte", "pára",
    "ihe", "basta", "peço", "esperem", "excelente", "entra", "cena",
    "trata", "liberdade", "dançar", "mentira", "alvo", "olhem", "max",
    "celular", "negro", "iremos", "super", "ora", "chamou", "vive",
    "comum", "rádio", "emergência", "inteligente", "animais", "maldição",
    "provar", "braço", "ficaria", "parecem", "herói", "livros", "aquelas",
    "km", "segure", "tornar", "havendo", "verão", "aceitar", "cozinha",
    "azul", "desejo", "faculdade", "chá", "receber", "época", "soldado",
    "clube", "banho", "tanta", "esperança", "américa", "bunda", "passei",
    "poderíamos", "ônibus", "vender", "és", "americano", "segura", "bolsa",
    "senhorita", "procura", "comandante", "aula", "preocupado", "mary",
    "perdido", "computador", "empresa", "sequer", "errada", "pôr",
    "carros", "seguinte", "mexa", "daquele", "vinho", "importo",
    "tínhamos", "solte", "jim", "esconder", "pego", "gostou", "humanos",
    "paris", "walter", "metros", "passando", "revisão", "tenham",
    "preocupar", "câmera", "perdão", "pele", "achamos", "várias", "cão",
    "parceiro", "uau", "principal", "diabo", "gelo", "mande", "toma",
    "defesa", "repente", "brincar", "lua", "prédio", "alta", "suspeito",
    "irão", "rainha", "passe", "dra", "inimigo", "roubar", "experiência",
    "cerca", "policiais", "ray", "departamento", "exceto", "cartas",
    "ficam", "viram", "piada", "soldados", "matei", "haverá", "cansado",
    "colocou", "morrendo", "roubou", "planos", "coragem", "manda",
    "diretor", "johnny", "pude", "nomes", "sejam", "pernas", "buraco",
    "sapatos", "escolher", "tirou", "gay", "imaginar", "entrada",
    "estação", "má", "cala", "prefiro", "mora", "pedido", "tornou",
    "subir", "meninas", "use", "pista", "destruir", "tia", "começando",
    "clark", "maldita", "perna", "nick", "cheia", "pedaço", "bala",
    "cadeia", "anel", "espírito", "dizia", "falamos", "vejam", "batalha",
    "conhecemos", "lidar", "contrário", "pegá", "novos", "parede", "longa",
    "costumava", "quieto", "almoço", "www", "mark", "peixe", "mentindo",
    "pergunte", "soubesse", "majestade", "líder", "fizer", "suponho",
    "cortar", "raiva", "evitar", "classe", "hei", "tamanho", "dança",
    "xerife", "praia", "richard", "enorme", "verde", "provas", "cor",
    "chaves", "fé", "pedindo", "chamam", "diante", "idiotas", "preparar",
    "encontre", "londres", "ganhou", "fantástico", "sabes", "pedra",
    "maluco", "gato", "mata", "novas", "limpar", "li", "brilhante",
    "apesar", "van", "agradeço", "vergonha", "gostava", "billy",
    "correndo", "cheguei", "laboratório", "bravo", "brincadeira", "bêbado",
    "chuck", "tommy", "arte", "grávida", "felizes", "nariz", "jovens",
    "vieram", "flores", "quão", "entregar", "eua", "natureza", "bobby",
    "coma", "dentes", "busca", "acesso", "terminou", "yeah", "filmes",
    "nervoso", "perdemos", "cuide", "responda", "siga", "abaixe", "criar",
    "esperto", "férias", "justiça", "danny", "dan", "ido", "relaxe",
    "pescoço", "dirigir", "relógio", "humana", "jornal", "animal", "total",
    "merece", "velhos", "escreveu", "restaurante", "contas", "debaixo",
    "vemos", "ridículo", "moça", "sabendo", "deixando", "agradecer",
    "beijo", "médicos", "pago", "tribunal", "americanos", "endereço",
    "interessa", "caminhão", "acalme", "corrida", "apresentar", "perdoe",
    "língua", "estrela", "branca", "escapar", "ponte", "percebi",
    "arrumar", "levantar", "nao", "usou", "faca", "amar", "julgamento",
    "pensava", "espada", "troca", "chegamos", "descobriu", "ruas",
    "parado", "perguntou", "especialmente", "will", "gostam", "visita",
    "série", "esqueceu", "cirurgia", "conhecia", "cadeira", "perdendo",
    "voar", "deram", "responder", "estaremos", "devíamos", "doença",
    "virá", "amava", "estranha", "daquela", "juiz", "salvo", "acordar",
    "atire", "grana", "ouve", "meninos", "levando", "milhares", "dado",
    "andy", "gentil", "machucar", "steve", "distância", "adoraria",
    "floresta", "vais", "infelizmente", "corra", "anna", "ficarei",
    "robert", "unidade", "disser", "oeste", "comece", "movimento",
    "carreira", "menor", "cinema", "caramba", "cavalheiros", "queres",
    "táxi", "virar", "barulho", "vôo", "you", "eric", "par", "imagino",
    "afinal", "conhecido", "vimos", "casado", "perfeita", "claire",
    "sentimentos", "acabado", "nacional", "inocente", "foder", "monstro",
    "cantar", "daniel", "luzes", "particular", "come", "estilo", "unidos",
    "comecei", "desapareceu", "parque", "lar", "chuva", "morre", "afaste",
    "discutir", "marca", "dedos", "corpos", "histórias", "navio", "éramos",
    "recebeu", "vire", "controlar", "fita", "besteira", "dono", "possamos",
    "depende", "major", "sobreviver", "noiva", "ficamos", "vento",
    "braços", "detalhes", "estados", "vindos", "traz", "firme", "madame",
    "noites", "raio", "poderiam", "clientes", "descer", "vítimas",
    "obviamente", "vídeo", "universidade", "absolutamente", "porco",
    "odeia", "sentado", "imbecil", "ganha", "avó", "imagem", "futebol",
    "comprou", "conheceu", "peso", "recebi", "confie", "querendo",
    "acorde", "calças", "ouvido", "fonte", "bolo", "espécie", "ryan",
    "princesa", "aeroporto", "altura", "verdadeira", "orgulho", "central",
    "quebrar", "comprei", "processo", "leite", "pete", "testemunha",
    "chorar", "dedo", "cai", "teoria", "serve", "correto", "estrelas",
    "acaso", "trocar", "descansar", "preto", "redor", "jerry", "contei",
    "apoio", "contente", "to", "decidir", "chamo", "encontrado", "kevin",
    "quisesse", "verá", "vossa", "direi", "cavalos", "nisto", "assistir",
    "universo", "briga", "camisa", "atrasado", "aberta", "forças",
    "ensinar", "divertir", "torna", "dão", "portas", "and", "veremos",
    "puxa", "pegamos", "ferido", "colega", "mapa", "seguindo", "atirou",
    "hum", "tomou", "livrar", "feche", "desistir", "agradável", "fantasma",
    "ameaça", "matando", "paga", "contrato", "liguei", "parada", "jogando",
    "leste", "matt", "cabo", "porcaria", "preparado", "bordo",
    "profissional", "culpado", "príncipe", "bateu", "morreram", "peito",
    "mandei", "escrito", "dói", "tiveram", "desculpem", "mentir",
    "corredor", "definitivamente", "desgraçado", "termos", "santo",
    "aparentemente", "podes", "juntar", "terão", "servir", "tirá", "al",
    "maravilhosa", "agir", "fugiu", "assistente", "perguntei", "militar",
    "dave", "lago", "bolas", "calor", "esquece", "visitar", "daria",
    "piloto", "motorista", "angeles", "peguem", "sinta", "deseja",
    "concordo", "acabamos", "posto", "presa", "larry", "casaco",
    "descobri", "interesse", "maiores", "arranjar", "sincronia", "cheque",
    "deixado", "traseiro", "pessoalmente", "mr", "okay", "babaca", "ted",
    "pensam", "chapéu", "achava", "passagem", "rabo", "viemos", "william",
    "serem", "inimigos", "garrafa", "sinais", "toca", "banda", "mexam",
    "caralho", "alice", "agentes", "largue", "baile", "deveriam", "jardim",
    "darei", "interessado", "senador", "vovó", "oferta", "lance", "venho",
    "perguntando", "cansada", "vadia", "encontraram", "preocupada",
    "câncer", "lsso", "avô", "consertar", "pequenos", "vivos", "casos",
    "malas", "chocolate", "feita", "sentiu", "aviso", "corre", "armário",
    "vingança", "respirar", "quebrou", "vencer", "funcionando", "carona",
    "lee", "aberto", "luke", "eie", "lisa", "mataram", "nasceu",
    "poderoso", "brian", "escolheu", "jason", "morar", "pau", "voltarei",
    "thomas", "estarão", "ovos", "copo", "balas", "casas", "pressa",
    "voltei", "baby", "atacar", "carl", "levo", "testes", "chamando",
    "fechado", "via", "sentem", "martin", "pertence", "ajudando", "arthur",
    "decidiu", "prestes", "voltando", "montanha", "demorar", "tratar",
    "rir", "oferecer", "imprensa", "chegaram", "fundos", "regra",
    "diversão", "dna", "tantas", "auto", "ficaram", "mato", "huh",
    "crédito", "explodir", "pacientes", "relacionamento", "deuses", "pôde",
    "adorável", "secreto", "queriam", "sexy", "ciência", "momentos",
    "jones", "chloe", "extra", "tô", "ultimamente", "pesquisa",
    "construir", "segredos", "impedir", "méxico", "roma", "enviar", "adam",
    "apaixonado", "vitória", "frança", "viajar", "mentiu", "primo",
    "temporada", "dane", "sujeito", "inglaterra", "jogos", "confusão",
    "gás", "kyle", "falam", "carter", "tantos", "alan", "emily", "campeão",
    "entrem", "humor", "desligar", "árvores", "levaram", "completo",
    "voltem", "califórnia", "pão", "devido", "mala", "tecnologia",
    "honesto", "respostas", "zona", "coloquei", "tirem", "internet",
    "data", "aulas", "explosão", "modelo", "mexer", "presos", "checar",
    "saí", "rosa", "colocá", "cães", "enfermeira", "canção", "tratamento",
    "aconteça", "bate", "escutar", "orgulhoso", "anjo", "avisar", "casal",
    "prometeu", "tempestade", "gênio", "don", "demônio", "roubo", "san",
    "decidi", "conhecem", "mel", "entrando", "tomando", "vc", "centenas",
    "ha", "joey", "curso", "comendo", "impressionante", "pegando",
    "francês", "annie", "propriedade", "acontecido", "transar", "nota",
    "rato", "entrevista", "nojento", "legendas", "recuperar", "neve",
    "perceber", "direitos", "invés", "pegaram", "torre", "smith", "cia",
    "vírus", "suicídio", "saberia", "complicado", "familiar", "treinador",
    "estejam", "rock", "médica", "poderes", "exame", "vinda", "presença",
    "material", "fronteira", "consiga", "efeito", "confio", "enviou",
    "mentiroso", "segurar", "admitir", "vegas", "alemães", "ganhei",
    "muda", "guardas", "escutem", "joga", "põe", "melhorar", "membro",
    "fumar", "costa", "contando", "limpa", "deserto", "seremos", "comeu",
    "encontra", "cigarro", "prepare", "vermelha", "acampamento", "jenny",
    "helicóptero", "new", "pequenas", "prêmio", "fossem", "tentativa",
    "parecido", "atender", "passamos", "reino", "vestir", "podíamos",
    "revista", "jogue", "prender", "identidade", "presentes", "ladrão",
    "famoso", "ande", "tido", "dom", "golpe", "incêndio", "topo",
    "conhecimento", "crescer", "dura", "ligando", "gritar", "aprendi",
    "usá", "começamos", "preocupa", "televisão", "suba", "partido",
    "sexual", "intenção", "inútil", "calmo", "deixaram", "homicídio",
    "rose", "chances", "truque", "gordo", "levem", "pagou", "soa",
    "chorando", "comportamento", "phil", "membros", "vivendo",
    "trabalhava", "dará", "fortes", "federal", "bando", "neles", "temo",
    "queijo", "pânico", "violência", "conseguia", "mantê", "pergunto",
    "sir", "montanhas", "social", "amigas", "fingir", "matado", "ouçam",
    "desligue", "ensinou", "óculos", "diário", "jogou", "chato", "voltará",
    "howard", "combate", "daqueles", "terceira", "últimas", "passaram",
    "pouquinho", "assinar", "prefeito", "jornais", "cobertura", "deixo",
    "leia", "aceita", "americana", "santa", "discurso", "razões", "caça",
    "tolo", "choque", "queda", "humanidade", "trazê", "adora", "insubs",
    "vaca", "famílias", "talento", "piscina", "mentiras", "escondendo",
    "impressão", "deixarei", "pássaro", "pedaços", "motor", "episódio",
    "solta", "primeiros", "dormiu", "perfeitamente", "geralmente", "canto",
    "ministro", "imagine", "reserva", "importantes", "deva", "coloca",
    "funeral", "trato", "pedras", "ed", "dirigindo", "sono", "estúpida",
    "confia", "grace", "completa", "notas", "devolver", "duvido",
    "tirando", "ruins", "envolvido", "cego", "tiros", "sara", "sozinhos",
    "começaram", "negros", "confuso", "senta", "carga", "alemão", "dean",
    "abby", "seguida", "corda", "ouvidos", "milagre", "simon", "enfim",
    "poderemos", "levará", "felicidade", "companheiro", "fizesse",
    "fábrica", "recado", "assustador", "ossos", "adiante", "garantir",
    "entrei", "iorque", "teatro", "esperamos", "cofre", "canal", "mandado",
    "resultados", "ato", "ferro", "pensado", "gasolina", "consciência",
    "ajudem", "céus", "morra", "ache", "documentos", "sentia", "caindo",
    "conseguem", "mundial", "red", "victor", "respire", "acordado",
    "inacreditável", "big", "telhado", "sofá", "idéias", "crimes",
    "acabaram", "treinamento", "susan", "in", "pesadelo", "baixa", "pizza",
    "mano", "permitir", "recentemente", "especiais", "estranhos", "virou",
    "loucos", "lutando", "leu", "tomei", "arriscar", "entanto", "entregue",
    "levei", "estudar", "dama", "registros", "pede", "digamos", "espelho",
    "procure", "século", "criou", "io", "fatos", "papo", "cabeças",
    "grave", "compras", "quiserem", "ouviram", "portão", "escondido",
    "oficiais", "vidro", "chamá", "pesado", "quebrado", "escuridão",
    "favorito", "assassinos", "conto", "aprendeu", "confortável",
    "equipamento", "acontecerá", "passeio", "acharam", "stan", "apostar",
    "russo", "lendo", "fazenda", "covarde", "página", "colegas", "ocupada",
    "original", "mover", "mova", "ficado", "negra", "bebe", "entrega",
    "terem", "trabalhou", "amizade", "beijar", "vovô", "mágica", "miami",
    "iguais", "câmeras", "câmara", "nathan", "tim", "câmbio", "elevador",
    "house", "vejamos", "remédio", "abram", "tento", "convidado",
    "estômago", "levanta", "ficava", "pareço", "julie", "juntas",
    "armadilha", "saudades", "deixam", "teus", "cuido", "roger", "lucy",
    "más", "china", "aposta", "testemunhas", "agência", "garotinha",
    "avise", "beba", "haja", "destes", "fechada", "folga", "máquinas",
    "deixaria", "leis", "perde", "miss", "urso", "bombas", "difíceis",
    "vantagem", "lavar", "rindo", "transporte", "dêem", "areia",
    "conversamos", "sorriso", "imaginei", "falava", "professora", "of",
    "vêem", "comunidade", "certas", "registro", "andrew", "pareceu",
    "sabiam", "sumiu", "engano", "lily", "pensamentos", "jesse", "castelo",
    "teto", "solo", "desculpar", "usam", "divertindo", "bagunça",
    "gigante", "selvagem", "bebendo", "imagina", "pôs", "bilhete",
    "malditos", "casada", "magia", "conversando", "macaco", "burro",
    "dragão", "garganta", "massa", "devesse", "levado", "acertar",
    "interior", "negativo", "superior", "jogada", "imagens", "claramente",
    "limite", "verei", "continuem", "doug", "kelly", "nervosa", "surpreso",
    "uniforme", "bairro", "texas", "buscá", "houver", "deviam", "fuga",
    "tirei", "laura", "alarme", "inverno", "dorme", "enfrentar", "lois",
    "entendendo", "pensamos", "custa", "ambulância", "terminei", "artista",
    "fantasia", "sede", "doido", "fã", "depósito", "lados", "artigo",
    "assustado", "cavalheiro", "gritando", "ilegal", "cópia", "viria",
    "nação", "edifício", "desafio", "roubado", "obra", "ligações",
    "marcas", "milhas", "placa", "paredes", "vivem", "convidados", "lorde",
    "papéis", "criatura", "coincidência", "esquisito", "cela", "possam",
    "pulso", "escrevi", "obter", "judeus", "praticamente", "secreta",
    "causar", "tragam", "moda", "acabo", "terno", "percebe", "próprias",
    "palco", "olhou", "prometi", "maravilha", "possibilidade", "bobagem",
    "colégio", "receio", "hank", "el", "defender", "marcus", "passos",
    "assalto", "chegue", "reação", "virgem", "casou", "saberá",
    "basicamente", "louis", "voltamos", "sombra", "promessa",
    "importância", "jogador", "legenda", "mina", "bebidas", "cura",
    "relaxar", "bebês", "rick", "gerente", "raios", "cuida", "morrido",
    "ouço", "explica", "entenda", "robin", "inspetor", "ta", "fugindo",
    "hmm", "salvá", "sentimento", "horário", "evento", "alegria", "oceano",
    "disco", "preparem", "vizinhos", "mudando", "ficaremos", "garagem",
    "cruel", "sopa", "corta", "conheça", "madeira", "assuntos", "prefere",
    "porão", "amante", "acreditam", "frango", "enganar", "prisioneiros",
    "irmãs", "anti", "on", "escada", "bobo", "paciência", "acorda",
    "divórcio", "tanque", "leo", "meter", "noivo", "desaparecer", "raça",
    "compromisso", "city", "alunos", "bastardo", "barry", "salve",
    "terminamos", "vice", "fria", "cuidando", "sorvete", "quadro", "peças",
    "compreendo", "limites", "partida", "sal", "glória", "caixas", "roy",
    "brancos", "mensagens", "veículo", "percebeu", "nadar", "joelhos",
    "quartos", "tropas", "estragar", "amém", "dividir", "prisioneiro",
    "aviões", "dava", "cheira", "período", "museu", "mágico", "prostituta",
    "alemanha", "desastre", "jackie", "pular", "elizabeth", "russos",
    "biblioteca", "áfrica", "afastem", "harvey", "vira", "acabe", "mudei",
    "legais", "judeu", "hã", "sofrimento", "garanto", "senso", "terry",
    "torta", "açúcar", "bruxa", "pacote", "pensamento", "park", "greg",
    "matéria", "betty", "fumaça", "conseguiram", "sigam", "adivinhar",
    "linhas", "cobra", "guarde", "tripulação", "andou", "evidências",
    "falado", "acalmar", "saudável", "educação", "aparência", "atravessar",
    "paraíso", "tentamos", "goste", "mac", "wilson", "jean", "segue", "pó",
    "criminoso", "pênis", "termina", "unidades", "marinha", "advogados",
    "babá", "convencer", "lê", "enganado", "primavera", "tocando",
    "esquecido", "alcance", "ódio", "incomoda", "terroristas", "vindas",
    "antigos", "brigar", "adorei", "destruição", "francisco", "saímos",
    "irmos", "sugiro", "emma", "poderei", "katie", "gary", "galinha",
    "fantasmas", "ross", "destas", "estacionamento", "ferrar", "veneno",
    "doces", "vila", "atitude", "livres", "audiência", "assumir",
    "reputação", "nâo", "fred", "mistério", "máscara", "devolva", "st",
    "terras", "ricos", "noel", "drinque", "paixão", "karen", "túnel",
    "criado", "chamamos", "declaração", "possivelmente", "capa", "perdida",
    "lenda", "importar", "incluindo", "ambiente", "batendo", "recompensa",
    "desça", "lábios", "frota", "camarada", "diamantes", "julia",
    "protegê", "lucas", "crise", "ficha", "excelência", "baseado",
    "teríamos", "molly", "voando", "it", "motivos", "fio", "queimar",
    "maus", "cachorros", "vigilância", "uísque", "fase", "esquina",
    "metal", "connor", "campanha", "transformar", "medicina", "segui",
    "proposta", "tocou", "piores", "disposto", "lembranças", "terapia",
    "vince", "bruce", "larga", "johnson", "iam", "teriam", "atirador",
    "júri", "atraso", "imperador", "assistindo", "bicicleta", "governador",
    "parker", "escapou", "combustível", "ferida", "poucas", "afastar",
    "soltar", "gostosa", "prato", "relações", "hitler", "salão",
    "superfície", "extremamente", "fortuna", "virem", "josh", "aluguel",
    "pássaros", "peitos", "certos", "temperatura", "pobres", "vampiros",
    "abençoe", "casey", "aérea", "nate", "deixamos", "facilmente",
    "amanda", "anteriormente", "donna", "moro", "resta", "farão", "onda",
    "gordon", "wayne", "escadas", "chamas", "cole", "aliança", "randy",
    "robô", "partiu", "boston", "academia", "graus", "chamei", "danos",
    "febre", "assustada", "chateado", "apaixonada", "lobo", "trabalhei",
    "patrick", "maggie", "dúvidas", "caneta", "honestamente", "festas",
    "atraente", "peixes", "dirá", "bata", "acertou", "convidou", "pura",
    "levarei", "imaginação", "genial", "dissesse", "lex", "marshall",
    "marty", "janelas", "mataria", "hollywood", "brava", "tiras", "dente",
    "ponta", "adorar", "ratos", "esquerdo", "escrevendo", "teddy", "forem",
    "competição", "eh", "militares", "sós", "esforço", "sofrer",
    "atingido", "terminado", "índia", "seriam", "álcool", "conseguiria",
    "maluca", "almoçar", "acordei", "dispositivo", "puro", "locais",
    "retirar", "correio", "criaturas", "instruções", "divirta", "cooper",
    "flor", "relaxa", "chegará", "sangrando", "casados", "escreve",
    "preocupação", "permita", "principalmente", "exames", "infeliz",
    "brown", "vinha", "armado", "feia", "almas", "formas", "corrente",
    "nasci", "vizinho", "mortes", "osso", "moral", "atrasada", "nascer",
    "brad", "anne", "clínica", "nuclear", "preparando", "alteza", "usei",
    "cometeu", "bella", "rota", "continuo", "alimentar", "cumprir",
    "infância", "corram", "concentrar", "acompanhar", "separar", "íamos",
    "queríamos", "voo", "civil", "cozinhar", "atacou", "calar",
    "chegarmos", "templo", "seres", "guerreiro", "ficarão", "tivessem",
    "souber", "vencedor", "causou", "procuro", "justin", "saído", "sally",
    "dexter", "valer", "aumentar", "face", "chamava", "policia", "dick",
    "durma", "perdoar", "perca", "recebemos", "região", "quebra", "puxe",
    "caçar", "acabando", "encher", "cinto", "terrorista", "remédios",
    "romântico", "bilhões", "aceite", "boneca", "repetir", "subindo",
    "mencionou", "curioso", "traidor", "morrem", "barriga", "moto",
    "usava", "quilômetros", "atirem", "saio", "convite", "responde",
    "sanduíche", "asas", "apagar", "leonard", "besta", "precise",
    "popular", "amostra", "cigarros", "bateria", "my", "helen", "sistemas",
    "guia", "secretária", "trabalhos", "território", "amei", "lágrimas",
    "engraçada", "botas", "escutando", "nessas", "jacob", "abrigo",
    "heróis", "superar", "maneiras", "campos", "vampiro", "planejando",
    "ocorreu", "brinde", "ciúmes", "prometa", "eis", "abandonar",
    "distante", "escolhido", "andem", "shawn", "iraque", "nesses",
    "assassinado", "miller", "estiverem", "estudante", "bíblia", "eia",
    "chinês", "cidades", "achá", "despedir", "papa", "romance", "calado",
    "ombro", "favorita", "inocentes", "cortou", "faltam", "machucou",
    "lata", "negociar", "escritor", "ouvimos", "achas", "delegacia",
    "criminosos", "charlotte", "condenado", "participar", "circunstâncias",
    "estúdio", "coroa", "kenny", "satélite", "pistas", "lou", "sentimos",
    "ator", "recebe", "king", "quieta", "carlos", "molho", "descubra",
    "aproximando", "namorados", "levantem", "mude", "resistência",
    "vendeu", "suco", "naves", "assassinatos", "pretende", "aproveitar",
    "colocando", "sofreu", "fresco", "agindo", "ás", "organização", "beth",
    "prima", "palácio", "porto", "moeda", "mm", "acusações", "tenhamos",
    "dirige", "preste", "gatilho", "dormi", "doutora", "ritmo", "deitar",
    "bond", "desaparecido", "marie", "apanhar", "especialista", "pública",
    "assustou", "aranha", "pecado", "óleo", "profundo", "mortal",
    "incomodar", "dona", "traiu", "piano", "sophie", "jordan", "segurando",
    "champanhe", "cresceu", "demônios", "votos", "mail", "normais",
    "encarar", "carol", "aliás", "assustar", "cargo", "acordou", "cobrir",
    "aquí", "mudaram", "cadáver", "atrasar", "encontrará", "turno",
    "recursos", "entendem", "positivo", "repito", "perigosa", "destruído",
    "lembrem", "saíram", "espião", "roubando", "nina", "oficialmente",
    "palhaço", "significado", "turma", "esconde", "matemática", "aldeia",
    "nobre", "eva", "man", "experimentar", "amamos", "esperei",
    "trabalham", "gata", "vendendo", "império", "médio", "incidente",
    "chegada", "custódia", "transmissão", "largar", "pastor", "lewis",
    "cartões", "vincent", "trabalhamos", "durar", "cruz", "cavaleiro",
    "pessoais", "desejar", "derek", "vivemos", "patrão", "bonitas",
    "cabelos", "parei", "gastar", "visual", "bauer", "nancy", "mandaram",
    "potter", "doc", "acusação", "gostoso", "acusado", "setor", "lady",
    "jamie", "tinta", "is", "suspeitos", "calça", "continuam", "discussão",
    "reconhece", "satisfeito", "steven", "mães", "libras", "dirija",
    "caminhar", "matem", "estranhas", "voto", "ficasse", "jaqueta",
    "união", "so", "comi", "vizinhança", "italiano", "privada", "comitê",
    "quilos", "corajoso", "retornar", "autoridades", "heroína", "collins",
    "traição", "pagando", "golfe", "capazes", "mental", "ondas", "avisei",
    "mortas", "aproveite", "construção", "falsa", "mantenham", "postos",
    "movendo", "levam", "procuramos", "espetáculo", "petróleo", "russell",
    "invasão", "ira", "federais", "angela", "decide", "daquelas", "aaron",
    "contado", "contratou", "considerando", "marcar", "miles", "segurem",
    "arrancar", "berlim", "amável", "interromper", "black", "procedimento",
    "damos", "puxar", "coluna", "compre", "vosso", "estudo", "estudos",
    "lindas", "prata", "crer", "atenda", "infecção", "albert", "vende",
    "portal", "adultos", "passam", "sócio", "pintura", "respondeu",
    "centavos", "tentaram", "ladrões", "sammy", "bandeira", "confirmar",
    "progresso", "leão", "sinceramente", "religião", "esperta", "visitas",
    "estudantes", "alcançar", "círculo", "sentada", "esperam", "gorda",
    "amam", "estivemos", "acontecem", "ovo", "coelho", "assusta",
    "urgente", "sensível", "gostando", "haviam", "falaram",
    "encontraremos", "tivéssemos", "trago", "multidão", "jornada",
    "acreditava", "batatas", "anterior", "ataques", "preparados", "penny",
    "aventura", "cadela", "virão", "maconha", "perdidos", "apresenta",
    "nascimento", "caos", "curar", "davis", "gatos", "eventos", "sobrou",
    "civis", "japão", "observando", "oxigênio", "prazo", "despedida",
    "impacto", "chegado", "ashley", "west", "cientistas", "vier", "puto",
    "sapato", "potencial", "delicioso", "voltaremos", "menti", "hill",
    "vazia", "white", "agenda", "todd", "egoísta", "lealdade", "espanhol",
    "rodas", "recebendo", "olivia", "rezar", "martha", "jay", "ethan",
    "cantando", "prá", "companheiros", "escreva", "rússia", "aguentar",
    "plástico", "cerebral", "br", "corações", "suportar", "promete",
    "orgulhosa", "tava", "gostamos", "dançando", "demos", "solitário",
    "ofereceu", "tratado", "comissão", "filhas", "derrubar", "liz",
    "concorda", "abertos", "abaixem", "caia", "achando", "clima",
    "cardíaco", "feitas", "fotografia", "escolhi", "oliver", "gangue",
    "culpar", "enviado", "vomitar", "frankie", "interessada", "amanhecer",
    "conferência", "caverna", "suspeita", "lançamento", "caridade",
    "limpeza", "promotor", "fingindo", "treinar", "morrerá", "laranja",
    "combinação", "treino", "atirando", "termine", "sagrado", "enganou",
    "símbolo", "doentes", "ficarem", "internacional", "stark", "disparar",
    "acreditamos", "descanso", "tracy", "matthew", "fígado", "correu",
    "mandando", "pistola", "salto", "street", "trânsito", "creme",
    "salada", "colar", "envolver", "sacrifício", "convidar", "tênis",
    "plantas", "rita", "jennifer", "duplo", "lincoln", "lawrence",
    "cabana", "considerar", "sabíamos", "desenho", "barba", "rebecca",
    "meias", "clay", "procurei", "atual", "expressão", "professores",
    "voltaram", "aperte", "castigo", "decente", "escutei", "miserável",
    "adivinha", "zangado", "iriam", "descanse", "cola", "jóias", "letra",
    "luvas", "césar", "bandidos", "assine", "logan", "cerimônia", "troco",
    "mira", "destruiu", "levaria", "stephen", "compartilhar", "patético",
    "deixará", "recepção", "começam", "contagem", "imploro", "earl",
    "suja", "emoções", "demora", "amigão", "joseph", "caçador",
    "computadores", "revolução", "receita", "walker", "pudéssemos",
    "machuque", "tentado", "abandonou", "cidadãos", "combinado",
    "poderosa", "sobreviveu", "informar", "munição", "sonhando", "piadas",
    "viesse", "esquadrão", "monstros", "lidando", "aproximar", "resolvido",
    "saibam", "anjos", "parecendo", "biscoitos", "sairá", "docinho",
    "azar", "allison", "cacete", "usamos", "visse", "times", "grau",
    "produção", "selva", "tornando", "gravação", "haveria", "holly",
    "colegial", "evan", "psiquiatra", "escolhe", "células", "cultura",
    "imaginando", "protegendo", "vaga", "reféns", "piedade", "grama",
    "frase", "xixi", "banheira", "negar", "kitty", "anúncio", "tragédia",
    "cientista", "refeição", "perfil", "comercial", "aumento", "frodo",
    "atriz", "michelle", "perderam", "paguei", "ansioso", "explique",
    "absurdo", "deter", "detesto", "transferência", "produto", "kent",
    "escravos", "concentre", "flórida", "motel", "vigiando", "passageiros",
    "almirante", "amado", "faltando", "chateada", "ganhando", "espacial",
    "condado", "entramos", "excitante", "cancelar", "demorou", "aceitou",
    "cemitério", "adulto", "objeto", "pesada", "colocado", "aguarde",
    "eli", "rotina", "músicas", "pecados", "bêbada", "curta", "existência",
    "muro", "cores", "ian", "países", "nascido", "ambas", "seguiu",
    "andei", "kirk", "ooh", "dobro", "dupla", "solteiro", "coleção",
    "amarelo", "geladeira", "gentileza", "pílulas", "apostas", "líderes",
    "atira", "ótimos", "cabine", "cometer", "jonathan", "serena", "cinzas",
    "conseguirá", "porcos", "impressões", "libertar", "rumo", "jogadores",
    "kg", "resistir", "oscar", "sid", "roubei", "apertar", "quietos",
    "ferramentas", "devêssemos", "exterior", "benjamin", "personalidade",
    "dose", "repórter", "sermos", "merdas", "tema", "trouxeram",
    "condicional", "pinto", "sincero", "poço", "dennis", "desista",
    "terror", "ficarmos", "emprestado", "descobrimos", "chase",
    "aconteceria", "queixa", "telefonema", "população", "pedimos",
    "secretário", "estrutura", "leitura", "brinquedos", "confissão",
    "sobe", "lembrança", "importaria", "seios", "houvesse", "descendo",
    "sobrinho", "queimando", "séria", "margaret", "ann", "planejado",
    "envie", "senha", "gostaríamos", "abri", "novidade", "parentes",
    "grupos", "fascinante", "ando", "acreditei", "patrulha", "gus",
    "circo", "existir", "peru", "respirando", "lana", "poderão",
    "transformou", "gays", "ned", "doer", "traficante", "lane", "possui",
    "estiveram", "permanecer", "ajudaria", "rica", "beco", "tatuagem",
    "primeiras", "dores", "gravata", "chamadas", "shane", "apressar",
    "macacos", "adolescente", "capital", "séculos", "personagem",
    "tradição", "mando", "feridos", "jersey", "assinatura", "mudam",
    "emoção", "canalha", "meritíssimo", "seth", "tristeza", "truques",
    "francamente", "literalmente", "blair", "ganhamos", "gabinete",
    "perímetro", "lama", "dylan", "pagam", "jedi", "adoram", "vendedor",
    "rude", "enterrado", "importam", "alternativa", "entraram", "nuvens",
    "mitchell", "cometi", "únicos", "precisará", "colocaram", "chip",
    "daisy", "manhattan", "escutou", "tribo", "tuas", "selvagens",
    "entregou", "espíritos", "voltaria", "montar", "falarei", "vivia",
    "embaixador", "medida", "prendê", "unhas", "carregando", "machucado",
    "passaporte", "decidimos", "mereço", "cocaína", "von", "dano",
    "aparelho", "ellie", "efeitos", "caixão", "lindos", "harold",
    "político", "angel", "sentença", "concordar", "adianta", "dólar",
    "mochila", "neil", "desejos", "desconhecido", "detê", "páginas",
    "ford", "ocasião", "assegurar", "roubaram", "trazido", "vozes",
    "representa", "contratar", "iniciar", "pulmões", "proibido", "ho",
    "global", "up", "bosta", "metrô", "túmulo", "megan", "erva", "meteu",
    "walt", "descoberta", "custar", "atingir", "min", "little", "radiação",
    "mexe", "nua", "manteiga", "mencionar", "apresse", "venceu", "manual",
    "viajando", "experiências", "espanha", "amostras", "aéreo", "preta",
    "produtos", "fraude", "viagens", "bebeu", "coca", "confessar",
    "machucá", "campeonato", "stanley", "brooke", "tivermos", "sugere",
    "jill", "trazendo", "águas", "capítulo", "velhas", "fantástica",
    "cansei", "formos", "mentes", "aço", "ronnie", "all", "acordada",
    "lenny", "mudado", "infantil", "empregados", "terreno", "seca",
    "ótimas", "conde", "prove", "elena", "alienígena", "tiroteio",
    "catherine", "índios", "ron", "parados", "perdedor", "fitas", "gado",
    "näo", "rocky", "distrito", "itália", "durão", "julgar", "atrasados",
    "movimentos", "reconhecer", "sintomas", "xícara", "usada", "sofrendo",
    "grant", "passear", "voltado", "fãs", "lançar", "encontrarmos",
    "keith", "tomo", "tapete", "estaríamos", "dale", "folha", "canadá",
    "torno", "caroline", "green", "contatos", "jess", "sue", "orelha",
    "achado", "barra", "notou", "wendy", "willie", "ala", "elegante",
    "franceses", "saem", "falhou", "mickey", "zoe", "azuis", "adorava",
    "óptimo", "brinquedo", "beisebol", "ajudo", "deverá", "inveja",
    "stone", "níveis", "sujeira", "explodiu", "demasiado", "reunir",
    "moedas", "formar", "solto", "famosa", "linguagem", "joguei",
    "cretino", "controla", "custou", "mísseis", "colocamos", "case",
    "faziam", "digital", "informado", "mostrando", "quebrada", "indústria",
    "saltar", "crescendo", "chute", "prometer", "go", "diego", "matam",
    "gina", "pensem", "viveu", "exercício", "atende", "esperanças",
    "tecido", "pretendo", "sentados", "coordenadas", "bati", "alegre",
    "perseguindo", "vingar", "sombras", "sydney", "by", "parceiros",
    "firma", "solar", "soltem", "trabalhadores", "fodido", "façamos",
    "química", "trauma", "preparada", "estratégia", "arrepender",
    "recorde", "ensaio", "prossiga", "ja", "orelhas", "ramo", "shopping",
    "odiar", "presumo", "igualmente", "termo", "escondeu", "tremendo",
    "buracos", "whoa", "influência", "vestindo", "sabor", "planta",
    "sortudo", "ignorar", "toalha", "velas", "solitária", "marco", "arroz",
    "raro", "profissão", "tiraram", "daremos", "horríveis", "vanessa",
    "destruí", "christine", "ideal", "tomada", "aguenta", "andam",
    "pudermos", "cruzar", "encontros", "origem", "acreditou", "miguel",
    "daquilo", "separados", "novidades", "escudo", "saberemos", "hannah",
    "arco", "empresas", "minas", "chore", "raymond", "ensino", "formatura",
    "parto", "viciado", "bagagem", "comemorar", "investigando", "inventou",
    "deite", "considere", "chegarem", "drama", "pratos", "odiava",
    "preocupados", "ingressos", "notar", "mexendo", "posse", "owen",
    "bocado", "disfarce", "reclamar", "reforços", "recém", "rosas",
    "economia", "chamem", "informante", "preocupo", "impedi", "junte",
    "pam", "tranquilo", "suficientes", "cidadão", "aproximadamente",
    "williams", "harvard", "praticar", "rumores", "sonhei", "pescar",
    "roteiro", "recusar", "ken", "percebo", "perfume", "ana", "república",
    "aluno", "realizar", "conselhos", "kong", "conhecida", "loira",
    "terríveis", "feitiço", "pausa", "despedido", "estivessem", "palmer",
    "intervalo", "ideias", "pareça", "invisível", "insetos", "códigos",
    "letras", "isca", "políticos", "doenças", "curiosidade", "limpe",
    "sobrevivência", "cordas", "sobrenome", "basquete", "sobreviventes",
    "esclarecer", "advogada", "curtis", "cocô", "senado", "beira",
    "compreender", "arrume", "sairmos", "jessica", "apropriado", "duke",
    "crânio", "suave", "centavo", "fontes", "direta", "importava",
    "pintar", "barcos", "juízo", "arruinar", "esperado", "perdê",
    "palpite", "folhas", "lembram", "refém", "jin", "barney", "colin",
    "escolas", "jen", "shaw", "explosivos", "figura", "antigas",
    "compreende", "equipes", "celebrar", "novato", "lentamente",
    "eternidade", "canta", "profundamente", "altos", "seco", "atualmente",
    "juan", "natalie", "finais", "boy", "tubo", "empurre", "nora",
    "matamos", "guerreiros", "franco", "notei", "damas", "elliot",
    "simpático", "bonitos", "cirurgião", "karl", "físico", "falhar", "age",
    "cassino", "confusa", "furioso", "botar", "harris", "pelotão",
    "reconhecimento", "jeremy", "pato", "reis", "violento", "acabam",
    "russa", "sandy", "jornalista", "concurso", "medalha", "juramento",
    "partindo", "mantendo", "coloquem", "riscos", "telefones", "áreas",
    "bruxas", "reverendo", "ajudará", "plataforma", "vagabunda", "co",
    "bebo", "lutou", "movam", "motores", "soco", "alexander", "cria",
    "armados", "comem", "estarem", "audrey", "permitido", "spencer",
    "quanta", "april", "quinn", "reuniões", "estudando", "tess", "ferir",
    "documento", "entenderam", "criando", "nicky", "samantha", "dica",
    "falaremos", "nojo", "francesa", "artes", "solteira", "encrenca",
    "conspiração", "procurado", "instinto", "lança", "festival",
    "fraqueza", "vós", "chegam", "funcionários", "apareça", "clássico",
    "katherine", "elétrica", "ellen", "bombeiros", "congresso", "surra",
    "beije", "cuidarei", "percy", "tortura", "ponham", "pediram", "poeira",
    "lojas", "sejamos", "caminhonete", "sonny", "testemunhar", "brigando",
    "bishop", "confidencial", "menores", "sobremesa", "precisaremos",
    "maquiagem", "apresento", "mijar", "paramos", "anthony", "recente",
    "lido", "chamaram", "comprando", "namorando", "convencê", "prenda",
    "monsieur", "bondade", "wallace", "admito", "nicole", "derrotar",
    "blá", "baleado", "unir", "trono", "boba", "estragou", "irem",
    "escolhas", "adivinhe", "estarmos", "honesta", "one", "cal", "rocha",
    "escrita", "pesadelos", "trilha", "enfiar", "batida", "fuja",
    "entendemos", "encontrem", "fechados", "sorria", "revistas",
    "razoável", "interesses", "escravo", "trailer", "voltarmos", "apuros",
    "holmes", "cobre", "maleta", "costume", "sabedoria", "garotinho",
    "sorrir", "pus", "kit", "joelho", "abertura", "prestar", "importe",
    "grato", "tina", "quentes", "desaparece", "tonto", "robôs", "maçã",
    "luxo", "empregada", "abandonado", "apontar", "tanques", "casei",
    "extraordinário", "rob", "alguem", "promoção", "esposas",
    "desagradável", "apertado", "questões", "aguente", "construiu",
    "japoneses", "profissionais", "juventude", "ocupados", "supostamente",
    "sábio", "educado", "estátua", "caído", "felizmente", "filmar",
    "sheldon", "meios", "ferimento", "restos", "descoberto", "salvei",
    "blake", "ligarei", "tigre", "refere", "durmo", "anderson", "cameron",
    "invadir", "atingiu", "emocionante", "aproxime", "imaginava",
    "preferia", "estariam", "encontrada", "repita", "esqueçam", "morando",
    "arranjou", "chinesa", "iríamos", "fiança", "rodada", "tumor",
    "louise", "procurou", "encontrarei", "cheios", "fama", "formação",
    "poesia", "doida", "sentiria", "cresci", "emprestar", "garantia",
    "vestidos", "comunicar", "quartel", "chegaremos", "hal", "conjunto",
    "certifique", "seguido", "gene", "protocolo", "transando", "castle",
    "rex", "administração", "incomum", "editor", "errados", "demitido",
    "avenida", "dai", "victoria", "sexuais", "morava", "minta", "franklin",
    "toby", "ciente", "trevas", "telefonar", "sirva", "preocupem", "luto",
    "programas", "objetos", "altamente", "impressionado", "virei",
    "conseguido", "precioso", "proteja", "gracinha", "possibilidades",
    "irritado", "fiel", "descobriram", "metro", "eletricidade", "torcida",
    "absoluta", "apoiar", "culpada", "mason", "brinca", "posições",
    "francis", "chineses", "intenções", "feridas", "lobos", "considerado",
    "alvos", "empregado", "cópias", "observação", "christian",
    "distintivo", "incríveis", "aproxima", "poema", "caí", "merecem",
    "ctu", "armazém", "eliminar", "mandá", "depoimento", "galera",
    "colina", "radar", "enormes", "mentirosa", "mama", "hall", "matarei",
    "couro", "bandido", "atmosfera", "pesquisas", "queima", "batata",
    "chutar", "ferimentos", "spock", "fox", "bush", "alienígenas",
    "protesto", "comecem", "taco", "precisaria", "ingleses", "tensão",
    "tubarão", "janet", "cristal", "adrian", "levamos", "cuidados",
    "esporte", "bart", "lute", "bicha", "lembrei", "substituir",
    "divertida", "atividades", "tomado", "inconsciente", "rifle",
    "esconderijo", "votar", "pressentimento", "músculos", "indica",
    "oriente", "entram", "decidido", "revelar", "praga", "your", "quintal",
    "cody", "abrindo", "macho", "compaixão", "retirada", "cabra",
    "sorrindo", "fraca", "desenhos", "emocional", "independente", "mi",
    "conforme", "verdadeiros", "cu", "jogado", "homicídios", "britânico",
    "manteve", "servem", "scotty", "wall", "conseguirmos", "booth", "maya",
    "consulta", "lutador", "familiares", "costuma", "move", "queimado",

    # Stopwords pt (stopwords-iso), filtradas por forma
    "acerca", "alem", "algmas", "apos", "comprido", "cuja", "cujas",
    "cujo", "cujos", "desligado", "dezanove", "dezasseis", "dezassete",
    "dispoe", "dispoem", "diversa", "diversas", "diversos", "entao",
    "estejamos", "estivera", "estivermos", "estiveste", "estivestes",
    "estivéramos", "estivéssemos", "fazeis", "fazes", "foste", "fostes",
    "fôramos", "fôssemos", "hajam", "hajamos", "havemos", "houvemos",
    "houvera", "houveram", "houverei", "houverem", "houveremos",
    "houveria", "houveriam", "houvermos", "houverá", "houverão",
    "houveríamos", "houvessem", "houvéramos", "houvéssemos", "hão",
    "inicio", "ista", "iste", "maiorias", "mediante", "naquelas",
    "naqueles", "nestas", "nestes", "oitava", "oitavo", "paucas",
    "promeiro", "propios", "proprio", "puderam", "põem", "quereis",
    "queremas", "quinto", "quáis", "seríamos", "sexto", "sois", "sétima",
    "sétimo", "tambem", "tendes", "tivera", "tiverem", "tiveste",
    "tivestes", "tivéramos", "tém", "vens", "vossas", "vossos", "à",
}

# Caracteres específicos do português (acentos, cedilha, til)
CARACTERES_PT = set("ãõáàâéêíóôúçÃÕÁÀÂÉÊÍÓÔÚÇ")

# Padrões de palavras pt-BR (terminações comuns)
SUFIXOS_PT = [
    "ção", "ções", "mente", "oso", "osa", "ável", "ível", "inho", "inha",
    "ando", "endo", "indo", "ava", "iam", "aria", "eria", "eira", "eiro",
    "ança", "ença", "ório", "ória", "ário", "ária", "dade",
]

# Marcas ortográficas inequívocas de pt-BR dentro das palavras
# (caracteres exclusivos + dígrafos característicos)
MARCAS_PT_PALAVRA = set("ãõáàâéêíóôúçÃÕÁÀÂÉÊÍÓÔÚÇ")
DIGRAFOS_PT = ("nh", "lh", "ç", "ão", "ões")

# Palavras funcionais inequívocas de espanhol/inglês (não existem em pt-BR
# escrito correto). Cada ocorrência aplica penalidade ao score.
PALAVRAS_NAO_PT = {
    # Espanhol
    "el", "los", "las", "del", "pero", "más", "eso", "esa", "ese",
    "esos", "esas", "muy", "también", "tampoco", "cuando", "entonces",
    "qué", "dónde", "cuánto", "gracias", "hola", "niño", "niña",
    "año", "años", "después", "hacer", "tener", "tiempo", "noche",
    "día", "hombre", "mujer", "usted", "ustedes", "son", "eres", "soy",
    "ella", "ellas", "nosotros", "vosotros", "quién", "cómo",
    # Inglês
    "the", "and", "with", "for", "you", "your", "not", "have", "had",
    "they", "them", "their", "will", "would", "could", "should",
    "this", "that", "these", "those", "from", "was", "were", "been",
}


def _tem_marca_pt(palavra: str) -> bool:
    if any(c in MARCAS_PT_PALAVRA for c in palavra):
        return True
    return any(d in palavra for d in DIGRAFOS_PT)


def calcular_score_pt(texto: str) -> float:
    """Calcula um score de 0 a 100 indicando probabilidade de ser pt-BR."""
    if not texto or not texto.strip():
        return 0.0

    texto_lower = texto.lower()
    # Filtrar apenas palavras alfanuméricas (ignora números puros, URLs, códigos)
    palavras = [p for p in re.findall(r'\b\w+\b', texto_lower)
                if not p.isdigit() and len(p) > 1]

    if not palavras:
        return 0.0

    # 1. Score por palavras conhecidas (peso: 50%)
    palavras_pt = sum(1 for p in palavras if p in PALAVRAS_PT)
    score_palavras = (palavras_pt / len(palavras)) * 100

    # 2. Score por caracteres pt-BR no texto (peso: 10% — dilui em textos longos)
    chars_total = len(texto)
    chars_pt = sum(1 for c in texto if c in CARACTERES_PT)
    score_chars = (chars_pt / max(chars_total, 1)) * 100

    # 2b. Score por marcas pt-BR por palavra (peso: 15%)
    #     Acentos, til, cedilha e dígrafos nh/lh contam por PALAVRA,
    #     não diluídos no total de caracteres.
    com_marca = sum(1 for p in palavras if _tem_marca_pt(p))
    score_marcas = (com_marca / len(palavras)) * 100

    # 3. Score por sufixos pt-BR (peso: 15%)
    sufixos = sum(1 for p in palavras if any(p.endswith(s) for s in SUFIXOS_PT))
    score_sufixos = (sufixos / len(palavras)) * 100

    # 4. Bonus para textos curtos que têm pelo menos 1 palavra pt-BR
    palavras_pt_count = sum(1 for p in palavras if p in PALAVRAS_PT)
    bonus_curto = 0
    if len(palavras) <= 5 and palavras_pt_count > 0:
        bonus_curto = 15  # ajuda textos curtos legítimos

    # 5. Penalidade por palavras inequívocas de outros idiomas (máx -40)
    estranhas = sum(1 for p in palavras if p in PALAVRAS_NAO_PT)
    penalidade = min(estranhas * 4, 40)

    # Peso final ajustado
    score_final = (
        (score_palavras * 0.5)
        + (min(score_chars, 100) * 0.1)
        + (min(score_marcas, 100) * 0.15)
        + (score_sufixos * 0.15)
        + bonus_curto
        - penalidade
    )

    return max(min(score_final, 100.0), 0.0)


def validar_idioma(texto: str, threshold: float = 30.0) -> dict:
    """Valida se o texto está em pt-BR.

    Args:
        texto: Texto a validar
        threshold: Score mínimo para considerar pt-BR (padrão: 30)

    Returns:
        dict com 'ok' (bool), 'score' (float), 'idioma' (str)
    """
    score = calcular_score_pt(texto)
    ok = score >= threshold

    return {
        "ok": ok,
        "score": round(score, 2),
        "idioma": "pt-BR" if ok else "desconhecido",
        "threshold": threshold,
    }


def main():
    if len(sys.argv) > 1 and sys.argv[1] == "--stdin":
        texto = sys.stdin.read()
    elif len(sys.argv) > 1:
        texto = " ".join(sys.argv[1:])
    else:
        print("Uso: python validar_idioma.py \"texto\" ou echo \"texto\" | python validar_idioma.py --stdin")
        sys.exit(2)

    resultado = validar_idioma(texto)

    if resultado["ok"]:
        print(f"[OK] pt-BR detectado (score: {resultado['score']})")
        sys.exit(0)
    else:
        print(f"[FALHA] Não-pt-BR detectado (score: {resultado['score']}, threshold: {resultado['threshold']})")
        sys.exit(1)


if __name__ == "__main__":
    main()